<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\API\TWGBaseController;
use App\Http\Requests\TWGProjectRequest;
use App\Http\Resources\TWGResource;
use App\Models\TWGProject;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

class TWGController extends TWGBaseController
{
  /*  public function index(): AnonymousResourceCollection
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }*/


}
