<?php

return [
    [
        'name' => 'Don Mariano Marcos Memorial State University-North La Union-Main Campus',
        'inst_type' => 'SUC Main',
        'city' => 'Bacnotan',
        'province' => 'La Union',
        'region' => 'Region I',
        'website' => 'dmmmsu-nluc.org',
        'email' => 'dmmmsu@dmmmsu.edu.ph',
        'phone' => '(072) 242-5641; (072) 888-5354',
    ],
    [
        'name' => 'Mariano Marcos State University-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Batac City',
        'province' => 'Ilocos Norte',
        'region' => 'Region I',
        'website' => 'http://www.mmsu.edu.ph',
        'email' => 'op@mmsu.edu.ph',
        'phone' => '(077) 600-0459',
    ],
    [
        'name' => 'Pangasinan State University',
        'inst_type' => 'SUC Main',
        'city' => 'Lingayen',
        'province' => 'Pangasinan',
        'region' => 'Region I',
        'website' => 'www.psu.edu.ph',
        'email' => 'prpio@psu.edu.ph',
        'phone' => '(075) 523-1682; (075) 206-0804',
    ],
    [
        'name' => 'Ilocos Sur Polytechnic State College-Main Campus',
        'inst_type' => 'SUC Main',
        'city' => 'Candon City',
        'province' => 'Ilocos Sur',
        'region' => 'Region I',
        'website' => 'www.nlpsc.edu.ph',
        'email' => 'op@ispsc.edu.ph',
        'phone' => '(077) 644-0210',
    ],
    [
        'name' => 'Quirino State University',
        'inst_type' => 'SUC Main',
        'city' => 'Diffun',
        'province' => 'Quirino',
        'region' => 'Region II',
        'website' => 'www.qsu.edu.ph',
        'email' => 'info@qsu.edu.ph',
        'phone' => '(078) 692-7056; 0939 935 2052',
    ],
    [
        'name' => 'Bulacan Agricultural State College',
        'inst_type' => 'SUC Main',
        'city' => 'San Ildefonso',
        'province' => 'Bulacan',
        'region' => 'Region III',
        'website' => 'www.basc.edu.ph',
        'email' => 'info@basc.edu.ph',
        'phone' => '(044) 762-1427; (044) 762-0022',
    ],
    [
        'name' => 'Nueva Ecija University of Science and Technology-Gabaldon Campus',
        'inst_type' => 'SUC Main',
        'city' => 'Gabaldon',
        'province' => 'Nueva Ecija',
        'region' => 'Region III',
        'website' => 'neust.edu.ph',
        'email' => 'neustmain@neust.edu.ph',
        'phone' => '(044) 463-0226; (044) 464-3674',
    ],
    [
        'name' => 'Central Luzon State University',
        'inst_type' => 'SUC Main',
        'city' => 'Science City of Muñoz',
        'province' => 'Nueva Ecija',
        'region' => 'Region III',
        'website' => 'http://clsu.edu.ph',
        'email' => 'op@clsu.edu.ph / ovpret@clsu.edu.ph',
        'phone' => '(044) 456-0107; (044) 456-5188; (044) 456-5202',
    ],
    [
        'name' => 'Pampanga State Agricultural University',
        'inst_type' => 'SUC Main',
        'city' => 'Magalang',
        'province' => 'Pampanga',
        'region' => 'Region III',
        'website' => 'www.psau.edu.ph',
        'email' => 'officeofthepresident@psau.edu.ph / castech@psau.edu.ph',
        'phone' => '(045) 866-0800; (045) 343-4950; (045) 343-4959',
    ],
    [
        'name' => 'Tarlac Agricultural University',
        'inst_type' => 'SUC Main',
        'city' => 'Camiling',
        'province' => 'Tarlac',
        'region' => 'Region III',
        'website' => 'www.tau.edu.ph',
        'email' => 'presoffice@tau.edu.ph',
        'phone' => '(02) 934-0216',
    ],
    [
        'name' => 'Aurora State College of Technology',
        'inst_type' => 'SUC Main',
        'city' => 'Baler',
        'province' => 'Aurora',
        'region' => 'Region III',
        'website' => 'http://www.ascot.edu.ph',
        'email' => 'president@ascot.edu.ph',
        'phone' => '(042) 209-4354 (Baler); (02) 373-5318; (02) 416-8083 (Mla)',
    ],
    [
        'name' => 'Eastern Samar State University',
        'inst_type' => 'SUC Main',
        'city' => 'Borongan City',
        'province' => 'Eastern Samar',
        'region' => 'Region VIII',
        'website' => 'http://essu.edu.ph',
        'email' => 'info@essu.edu.ph',
        'phone' => '(055) 261-2725',
    ],
    [
        'name' => 'Southern Leyte State University',
        'inst_type' => 'SUC Main',
        'city' => 'Sogod',
        'province' => 'Southern Leyte',
        'region' => 'Region VIII',
        'website' => 'www.slsuonline.edu.ph',
        'email' => 'records@southernleytestateu.edu.ph',
        'phone' => '(053) 382-3294',
    ],
    [
        'name' => 'University of Eastern Philippines',
        'inst_type' => 'SUC Main',
        'city' => 'Catarman',
        'province' => 'Northern Samar',
        'region' => 'Region VIII',
        'website' => 'uep.edu.ph',
        'email' => 'uepnsofficial@uep.edu.ph',
        'phone' => '(055) 251-8611',
    ],
    [
        'name' => 'Visayas State University',
        'inst_type' => 'SUC Main',
        'city' => 'Baybay City',
        'province' => 'Leyte',
        'region' => 'Region VIII',
        'website' => 'www.vsu.edu.ph',
        'email' => 'information@vsu.edu.ph',
        'phone' => '(053) 563-7067',
    ],
    [
        'name' => 'Cavite State University-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Indang',
        'province' => 'Cavite',
        'region' => 'Region IV-A',
        'website' => 'www.cvsu.edu.ph',
        'email' => 'office.president@cvsu.edu.ph',
        'phone' => '(046) 415-0012; (046) 415-0010; (046) 415-0011',
    ],
    [
        'name' => 'Marinduque State University-Main Campus',
        'inst_type' => 'SUC Main',
        'city' => 'Boac',
        'province' => 'Marinduque',
        'region' => 'Region IV-B',
        'website' => 'https://marinduquestatecollege.edu.ph',
        'email' => 'president@mscmarinduque.edu.ph',
        'phone' => '(042) 332-2028',
    ],
    [
        'name' => 'Western Philippines University',
        'inst_type' => 'SUC Main',
        'city' => 'Aborlan',
        'province' => 'Palawan',
        'region' => 'Region IV-B',
        'website' => 'www.wpu.edu.ph',
        'email' => 'pres.office@wpu.edu.ph',
        'phone' => '(048) 433-4367; 0919-3836791; 0921-3769389; 0998-8686989',
    ],
    [
        'name' => 'Palawan State University',
        'inst_type' => 'SUC Main',
        'city' => 'Puerto Princesa City',
        'province' => 'Palawan',
        'region' => 'Region IV-B',
        'website' => 'http://www.psu.palawan.edu.ph',
        'email' => 'rdocto@psu.palawan.edu.ph',
        'phone' => '(048) 433-5303; (048) 433-2379',
    ],
    [
        'name' => 'Romblon State University-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Odiongan',
        'province' => 'Romblon',
        'region' => 'Region IV-B',
        'website' => 'www.rsu.edu.ph',
        'email' => 'romblonstateu@gmail.com',
        'phone' => '(042) 567-5271; (042) 567-5859; (042) 567-5273',
    ],
    [
        'name' => 'Aklan State University-Banga Campus',
        'inst_type' => 'SUC Main',
        'city' => 'Banga',
        'province' => 'Aklan',
        'region' => 'Region VI',
        'website' => 'www.asu.edu.ph',
        'email' => 'president@asu.edu.ph',
        'phone' => '(036) 267-5801',
    ],
    [
        'name' => 'Capiz State University-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Roxas City',
        'province' => 'Capiz',
        'region' => 'Region VI',
        'website' => 'www.capsu.edu.ph',
        'email' => 'admin@capsu.edu.ph',
        'phone' => '(036) 621-3514; (036) 621-4337; (036) 621-4311',
    ],
    [
        'name' => 'Guimaras State College-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Buenavista',
        'province' => 'Guimaras',
        'region' => 'Region VI',
        'website' => 'www1@gsc.edu.ph',
        'email' => 'university.president@gsu.edu.ph',
        'phone' => '(033) 580-8244; (033) 580-8245; (033) 580-8246',
    ],
    [
        'name' => 'Iloilo State College of Fisheries-Dingle and San Enrique Campus',
        'inst_type' => 'SUC Main',
        'city' => 'Barotac Nuevo',
        'province' => 'Iloilo',
        'region' => 'Region VI',
        'website' => 'http://www.iscof.edu.ph',
        'email' => 'iscofpresident@gmail.com',
        'phone' => '(033) 361-2369',
    ],
    [
        'name' => 'Northern Negros State College of Science and Technology',
        'inst_type' => 'SUC Main',
        'city' => 'Sagay City',
        'province' => 'Negros Occidental',
        'region' => 'Region VI',
        'website' => 'www.nonescost.edu.ph',
        'email' => 'ict@nonescost.edu.ph',
        'phone' => '(034) 722-4120',
    ],
    [
        'name' => 'Central Philippines State University-Main Campus',
        'inst_type' => 'SUC Main',
        'city' => 'Kabankalan City',
        'province' => 'Negros Occidental',
        'region' => 'Region VI',
        'website' => 'www.cpsu.edu.ph',
        'email' => 'officeofthepresident@cpsu.edu.ph',
        'phone' => '(034) 471-3045',
    ],
    [
        'name' => 'Northern Iloilo State University-Estancia, Iloilo',
        'inst_type' => 'SUC Main',
        'city' => 'Estancia',
        'province' => 'Iloilo',
        'region' => 'Region VI',
        'website' => 'www.nipsc.edu.ph',
        'email' => 'nisuadmin@nisu.edu.ph',
        'phone' => '(033) 397-0315; (033) 397-0314',
    ],
    [
        'name' => 'West Visayas State University-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Iloilo City',
        'province' => 'Iloilo',
        'region' => 'Region VI',
        'website' => 'http://www.wvsu.edu.ph',
        'email' => 'president@wvsu.edu.ph',
        'phone' => '(033) 320-0870 to77; (033) 320-0879; (033) 320-7793',
    ],
    [
        'name' => 'Iloilo Science and Technology University-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Iloilo City',
        'province' => 'Iloilo',
        'region' => 'Region VI',
        'website' => 'www.wvcst.edu.ph',
        'email' => 'mail@isatu.edu.ph',
        'phone' => '(033) 320-7190 loc 102; (033) 329-4274',
    ],
    [
        'name' => 'Camiguin Polytechnic State College',
        'inst_type' => 'SUC Main',
        'city' => 'Mambajao',
        'province' => 'Camiguin',
        'region' => 'Region X',
        'website' => 'www.cpsc.edu.ph',
        'email' => 'president@cpsc.edu.ph',
        'phone' => '(088) 387-1268; (088) 387-0044; (088) 387-0495',
    ],
    [
        'name' => 'Central Mindanao University',
        'inst_type' => 'SUC Main',
        'city' => 'Maramag',
        'province' => 'Bukidnon',
        'region' => 'Region X',
        'website' => 'www.cmu.edu.ph',
        'email' => 'cmu1910op@cmu.edu.ph',
        'phone' => '0917-7060347',
    ],
    [
        'name' => 'University of Science and Technology of Southern Philippines',
        'inst_type' => 'SUC Main',
        'city' => 'Cagayan De Oro City',
        'province' => 'Misamis Oriental',
        'region' => 'Region X',
        'website' => 'http://www.ustp.edu.ph',
        'email' => 'president.office@ustp.edu.ph',
        'phone' => '(088) 856-4696; (088) 856-1739',
    ],
    [
        'name' => 'Northwestern Mindanao State College of Science and Technology',
        'inst_type' => 'SUC Main',
        'city' => 'Tangub City',
        'province' => 'Misamis Occidental',
        'region' => 'Region X',
        'website' => 'www.nmsc.edu.ph',
        'email' => 'info@nmsc.edu.ph',
        'phone' => '(088) 586-0173',
    ],
    [
        'name' => 'Sultan Kudarat State University',
        'inst_type' => 'SUC Main',
        'city' => 'Tacurong City',
        'province' => 'Sultan Kudarat',
        'region' => 'Region XII',
        'website' => 'www.sksu.edu.ph',
        'email' => 'ict@sksu.edu.ph',
        'phone' => '(064) 200-7336; 0917-7770754',
    ],
    [
        'name' => 'University of Southern Mindanao-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Kabacan',
        'province' => 'North Cotabato',
        'region' => 'Region XII',
        'website' => 'www.usm.edu.ph',
        'email' => 'op@usm.edu.ph',
        'phone' => '(064) 248-2138; (064) 454-0175',
    ],
    [
        'name' => 'Abra State Institute of Science and Technology-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Lagangilang',
        'province' => 'Abra',
        'region' => 'Region XIV',
        'website' => 'http://www.asist.edu.ph',
        'email' => 'president@asist.edu.ph',
        'phone' => '(074) 752-8171',
    ],
    [
        'name' => 'Benguet State University-Main',
        'inst_type' => 'SUC Main',
        'city' => 'La Trinidad',
        'province' => 'Benguet',
        'region' => 'Region XIV',
        'website' => 'www.bsu.edu.ph',
        'email' => 'president@bsu.edu.ph',
        'phone' => '(074) 422-2127; (074) 422-2009; (074) 422-2401',
    ],
    [
        'name' => 'Ifugao State University - Main',
        'inst_type' => 'SUC Main',
        'city' => 'Lamut',
        'province' => 'Ifugao',
        'region' => 'Region XIV',
        'website' => 'www.ifsu.edu.ph',
        'email' => 'ifsu.cedlamutcampus@gmail.com',
        'phone' => '0917-5742363',
    ],
    [
        'name' => 'Agusan Del Sur State College of Agriculture and Technology',
        'inst_type' => 'SUC Main',
        'city' => 'Bunawan',
        'province' => 'Agusan Del Sur',
        'region' => 'Region XVI',
        'website' => 'http://asscat.edu.ph',
        'email' => 'op@asscat.edu.ph',
        'phone' => '0999-7490294',
    ],
    [
        'name' => 'Caraga State University-Main Campus',
        'inst_type' => 'SUC Main',
        'city' => 'Butuan City',
        'province' => 'Agusan Del Norte',
        'region' => 'Region XVI',
        'website' => 'http://www.carsu.edu.ph',
        'email' => 'op@carsu.edu.ph',
        'phone' => '(085) 342-3047; (085) 342-1079; (085) 341-8677',
    ],
    [
        'name' => 'RFO 1 - Ilocos Region',
        'inst_type' => 'DA Unit',
        'city' => 'San Fernando City',
        'province' => 'La Union',
        'region' => 'Region I',
        'website' => 'ilocos.da.gov.ph',
        'email' => 'ilocos@da.gov.ph; annieqbares@yahoo.com',
        'phone' => '(072) 242-1045; (072) 242-1046',
    ],
    [
        'name' => 'RFO Region I',
        'inst_type' => 'DA Unit',
        'city' => 'San Fernando',
        'province' => 'La Union',
        'region' => 'Region I',
        'website' => 'ilocos.da.gov.ph',
        'email' => 'ilocos@da.gov.ph; annieqbares@yahoo.com',
        'phone' => '(072) 242-1045; (072) 242-1046 local 06',
    ],
    [
        'name' => 'RFO Region II',
        'inst_type' => 'DA Unit',
        'city' => 'Tuguegarao City',
        'province' => 'Cagayan',
        'region' => 'Region II',
        'website' => 'ored.da.gov.ph',
        'email' => 'ored.rfo2@da.gov.ph',
        'phone' => '(078) 396-9769',
    ],
    [
        'name' => 'RFO Region III',
        'inst_type' => 'DA Unit',
        'city' => 'City of San Fernando',
        'province' => 'Pampanga',
        'region' => 'Region III',
        'website' => 'da.centralluzon.da.gov.ph',
        'email' => 'da.centralluzon@rfo3.da.gov.ph',
        'phone' => '(045) 961-3472; (045) 961-2631; (045) 961-3075',
    ],
    [
        'name' => 'RFO Region IV-A',
        'inst_type' => 'DA Unit',
        'city' => 'Lipa City',
        'province' => 'Batangas',
        'region' => 'Region IV-A',
        'website' => 'calabarzon.da.gov.ph',
        'email' => 'ored@calabarzon.da.gov.ph; rtd.operations@calabarzon.da.gov.ph',
        'phone' => '(02) 8928-8741 to 64 local 4471, 4480',
    ],
    [
        'name' => 'RFO Region IV-B',
        'inst_type' => 'DA Unit',
        'city' => 'Quezon City',
        'province' => 'Quezon City',
        'region' => 'Region IV-B',
        'website' => 'mimaropa.da.gov.ph',
        'email' => 'mimaropa@mail.da.gov.ph',
        'phone' => '(02) 8927-4350; (02) 8332-7274',
    ],
    [
        'name' => 'RFO Region V',
        'inst_type' => 'DA Unit',
        'city' => 'Pili',
        'province' => 'Camarines Sur',
        'region' => 'Region V',
        'website' => 'da5ored.yahoo.com',
        'email' => 'da5ored@yahoo.com',
        'phone' => '(054) 477-0381',
    ],
    [
        'name' => 'RFO Region VI',
        'inst_type' => 'DA Unit',
        'city' => 'Jaro',
        'province' => 'Iloilo',
        'region' => 'Region VI',
        'website' => 'westernvisayas.da.gov.ph',
        'email' => 'westernvisayas@mail.da.gov.ph',
        'phone' => '(033) 337-1262',
    ],
    [
        'name' => 'RFO Region VII',
        'inst_type' => 'DA Unit',
        'city' => 'Mandaue City',
        'province' => 'Cebu',
        'region' => 'Region VII',
        'website' => 'redsoffice7.yahoo.com',
        'email' => 'redsoffice7@yahoo.com; redsoffice7@gmail.com',
        'phone' => '(032) 268-5187; (032) 268-3063; (032) 238-2163',
    ],
    [
        'name' => 'RFO Region VIII',
        'inst_type' => 'DA Unit',
        'city' => 'Tacloban City',
        'province' => 'Leyte',
        'region' => 'Region VIII',
        'website' => 'da8ored1@gmail.com',
        'email' => 'da8ored1@gmail.com; da8ored@yahoo.com; da8resdiv@gmail.com',
        'phone' => '(053) 321-2024; (053) 832-0694; (053) 325-7242',
    ],
    [
        'name' => 'RFO Region IX',
        'inst_type' => 'DA Unit',
        'city' => 'Pagadian City',
        'province' => 'Zamboanga del Sur',
        'region' => 'Region IX',
        'website' => 'rfo9.mail.da.gov.ph',
        'email' => 'rfo9@mail.da.gov.ph',
        'phone' => '(062) 214-4677; (062) 991-3188 local 106; (062) 992-3201; (062) 214-4677; (062) 991-2536',
    ],
    [
        'name' => 'RFO Region X',
        'inst_type' => 'DA Unit',
        'city' => 'Cagayan de Oro City',
        'province' => 'Misamis Oriental',
        'region' => 'Region X',
        'website' => 'da10ored@gmail.com',
        'email' => 'da10ored@gmail.com',
        'phone' => '(088) 856-6871; (088) 856-2753 to 55',
    ],
    [
        'name' => 'RFO Region XI',
        'inst_type' => 'DA Unit',
        'city' => 'Davao City',
        'province' => 'Davao del Sur',
        'region' => 'Region XI',
        'website' => 'darfoxi.red@gmail.com',
        'email' => 'darfoxi.red@gmail.com',
        'phone' => '(082) 221-9697; (082) 226-3625 local 1100',
    ],
    [
        'name' => 'RFO Region XII',
        'inst_type' => 'DA Unit',
        'city' => 'Koronadal City',
        'province' => 'South Cotabato',
        'region' => 'Region XII',
        'website' => 'ored@rfo12.da.gov.ph',
        'email' => 'ored@rfo12.da.gov.ph',
        'phone' => '(083) 228-3413',
    ],
    [
        'name' => 'RFO Region XIII',
        'inst_type' => 'DA Unit',
        'city' => 'Butuan City',
        'province' => 'Agusan del Norte',
        'region' => 'Region XIII',
        'website' => 'caraga.mail.da.gov.ph',
        'email' => 'caraga@mail.da.gov.ph',
        'phone' => '(085) 341-4546; (085) 305-0092',
    ],
    [
        'name' => 'RFO CAR',
        'inst_type' => 'DA Unit',
        'city' => 'Baguio City',
        'province' => 'Benguet',
        'region' => 'CAR',
        'website' => 'car.da.gov.ph',
        'email' => 'da_carfu@yahoo.com',
        'phone' => '(074) 445-4973 / (074) 443-4621',
    ],
    [
        'name' => 'MAFAR BARRM',
        'inst_type' => 'DA Unit',
        'city' => 'Cotabato City',
        'province' => 'Cotabato',
        'region' => 'BARMM',
        'website' => 'bangsamoro.gov.ph',
        'email' => 'mafar@bangsamoro.gov.ph',
        'phone' => '(064) 421-1248; (064) 421-1234',
    ],
    [
        'name' => 'Philippine Rice Research Institute',
        'inst_type' => 'DA Unit',
        'city' => 'Science City of Muñoz',
        'province' => 'Nueva Ecija',
        'region' => 'Region III',
        'website' => 'philrice.gov.ph',
        'email' => 'prri.mail@philrice.gov.ph',
        'phone' => 'n/a',
    ],
    [
        'name' => 'Philippine Rootcrops Research Center',
        'inst_type' => 'DA Unit',
        'city' => 'Baybay City',
        'province' => 'Leyte',
        'region' => 'Region VIII',
        'website' => 'vsu.edu.ph',
        'email' => 'philrootcrops@vsu.edu.ph',
        'phone' => '63 (053) 565 0600 local 1063',
    ],
    [
        'name' => 'Bureau of Agricultural Research',
        'inst_type' => 'DA Unit',
        'city' => 'Quezon City',
        'province' => 'Quezon City',
        'region' => 'NCR',
        'website' => 'bar.gov.ph',
        'email' => 'jsoriano@bar.gov.ph',
        'phone' => '(02) 8461-2900 local 2029',
    ],
    [
        'name' => 'Bureau of Plant Industry',
        'inst_type' => 'DA Unit',
        'city' => 'Manila',
        'province' => 'Manila',
        'region' => 'NCR',
        'website' => 'buplant.da.gov.ph',
        'email' => 'bpi.do@buplant.da.gov.ph',
        'phone' => '(02) 8525-2987; (02) 8521-7650; (02) 8332-7567',
    ],
    [
        'name' => 'Philippine Fiber Industry Development Authority',
        'inst_type' => 'DA Unit',
        'city' => 'Quezon City',
        'province' => 'Quezon City',
        'region' => 'NCR',
        'website' => 'philfida.da.gov.ph',
        'email' => 'oed@philfida.da.gov.ph',
        'phone' => '(02) 8928-8741 to 64 local 2650',
    ],
    [
        'name' => 'National Tobacco Administration',
        'inst_type' => 'DA Unit',
        'city' => 'Quezon City',
        'province' => 'Quezon City',
        'region' => 'NCR',
        'website' => 'www.nta.da.gov.ph',
        'email' => 'n/a',
        'phone' => '(02) 8374-3987; (02) 8374-2025',
    ],
    [
        'name' => 'Philippine Coconut Authority',
        'inst_type' => 'DA Unit',
        'city' => 'Quezon City',
        'province' => 'Quezon City',
        'region' => 'NCR',
        'website' => 'pca.gov.ph',
        'email' => 'ofad@pca.gov.ph; pca.ofad@gmail.com',
        'phone' => '(02) 8927-8706; (02) 8927-8116; (02) 8921-3387 local 203, 205, 206',
    ],
    [
        'name' => 'Sugar Regulatory Administration',
        'inst_type' => 'DA Unit',
        'city' => 'Quezon City',
        'province' => 'Quezon City',
        'region' => 'NCR',
        'website' => 'sra.gov.ph',
        'email' => 'srahead@sra.gov.ph',
        'phone' => '(02) 8926-2928; (02) 8929-3633',
    ],
    [
        'name' => 'Philippine Rubber Research Institute',
        'inst_type' => 'DA Unit',
        'city' => 'DA Unit',
        'province' => 'Zamboanga Sibugay',
        'region' => 'Region IX',
        'website' => 'prri.da.gov.ph',
        'email' => 'cheryleusala@gmail.com; prrimain@gmail.com',
        'phone' => '(062) 055-1622; (02) 8928-8741 to 64 local 2255',
    ],
    [
        'name' => 'DA-Crop Biotechnology Center',
        'inst_type' => 'DA Unit',
        'city' => 'Science City of Muñoz',
        'province' => 'Nueva Ecija',
        'region' => 'Region III',
        'website' => 'philrice.gov.ph',
        'email' => 'cropbiotechcenter@gmail.com',
        'phone' => '09088897135',
    ],
];
