<?php

return [
    [
        'name' => 'Don Mariano Marcos Memorial State University-North La Union-Main Campus',
        'inst_type' => 'SUC Main',
        'city' => 'Bacnotan',
        'province' => 'La Union',
        'region' => '01 - Ilocos Region',
        'website' => 'dmmmsu-nluc.org',
        'email' => 'dmmmsu@dmmmsu.edu.ph',
        'phone' => '(072) 242-5641; (072) 888-5354',
    ],
    [
        'name' => 'Mariano Marcos State University-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Batac City',
        'province' => 'Ilocos Norte',
        'region' => '01 - Ilocos Region',
        'website' => 'http://www.mmsu.edu.ph',
        'email' => 'op@mmsu.edu.ph',
        'phone' => '(077) 600-0459',
    ],
    [
        'name' => 'Pangasinan State University',
        'inst_type' => 'SUC Main',
        'city' => 'Lingayen',
        'province' => 'Pangasinan',
        'region' => '01 - Ilocos Region',
        'website' => 'www.psu.edu.ph',
        'email' => 'prpio@psu.edu.ph',
        'phone' => '(075) 523-1682; (075) 206-0804',
    ],
    [
        'name' => 'Ilocos Sur Polytechnic State College-Main Campus',
        'inst_type' => 'SUC Main',
        'city' => 'Candon City',
        'province' => 'Ilocos Sur',
        'region' => '01 - Ilocos Region',
        'website' => 'www.nlpsc.edu.ph',
        'email' => 'op@ispsc.edu.ph',
        'phone' => '(077) 644-0210',
    ],
    [
        'name' => 'Quirino State University',
        'inst_type' => 'SUC Main',
        'city' => 'Diffun',
        'province' => 'Quirino',
        'region' => '02 - Cagayan Valley',
        'website' => 'www.qsu.edu.ph',
        'email' => 'info@qsu.edu.ph',
        'phone' => '(078) 692-7056; 0939 935 2052',
    ],
    [
        'name' => 'Bulacan Agricultural State College',
        'inst_type' => 'SUC Main',
        'city' => 'San Ildefonso',
        'province' => 'Bulacan',
        'region' => '03 - Central Luzon',
        'website' => 'www.basc.edu.ph',
        'email' => 'info@basc.edu.ph',
        'phone' => '(044) 762-1427; (044) 762-0022',
    ],
    [
        'name' => 'Nueva Ecija University of Science and Technology-Gabaldon Campus',
        'inst_type' => 'SUC Main',
        'city' => 'Gabaldon',
        'province' => 'Nueva Ecija',
        'region' => '03 - Central Luzon',
        'website' => 'neust.edu.ph',
        'email' => 'neustmain@neust.edu.ph',
        'phone' => '(044) 463-0226; (044) 464-3674',
    ],
    [
        'name' => 'Central Luzon State University',
        'inst_type' => 'SUC Main',
        'city' => 'Science City of Muñoz',
        'province' => 'Nueva Ecija',
        'region' => '03 - Central Luzon',
        'website' => 'http://clsu.edu.ph',
        'email' => 'op@clsu.edu.ph / ovpret@clsu.edu.ph',
        'phone' => '(044) 456-0107; (044) 456-5188; (044) 456-5202',
    ],
    [
        'name' => 'Pampanga State Agricultural University',
        'inst_type' => 'SUC Main',
        'city' => 'Magalang',
        'province' => 'Pampanga',
        'region' => '03 - Central Luzon',
        'website' => 'www.psau.edu.ph',
        'email' => 'officeofthepresident@psau.edu.ph / castech@psau.edu.ph',
        'phone' => '(045) 866-0800; (045) 343-4950; (045) 343-4959',
    ],
    [
        'name' => 'Tarlac Agricultural University',
        'inst_type' => 'SUC Main',
        'city' => 'Camiling',
        'province' => 'Tarlac',
        'region' => '03 - Central Luzon',
        'website' => 'www.tau.edu.ph',
        'email' => 'presoffice@tau.edu.ph',
        'phone' => '(02) 934-0216',
    ],
    [
        'name' => 'Aurora State College of Technology',
        'inst_type' => 'SUC Main',
        'city' => 'Baler',
        'province' => 'Aurora',
        'region' => '03 - Central Luzon',
        'website' => 'http://www.ascot.edu.ph',
        'email' => 'president@ascot.edu.ph',
        'phone' => '(042) 209-4354 (Baler); (02) 373-5318; (02) 416-8083 (Mla)',
    ],
    [
        'name' => 'Eastern Samar State University',
        'inst_type' => 'SUC Main',
        'city' => 'Borongan City',
        'province' => 'Eastern Samar',
        'region' => '08 - Eastern Visayas',
        'website' => 'http://essu.edu.ph',
        'email' => 'info@essu.edu.ph',
        'phone' => '(055) 261-2725',
    ],
    [
        'name' => 'Southern Leyte State University',
        'inst_type' => 'SUC Main',
        'city' => 'Sogod',
        'province' => 'Southern Leyte',
        'region' => '08 - Eastern Visayas',
        'website' => 'www.slsuonline.edu.ph',
        'email' => 'records@southernleytestateu.edu.ph',
        'phone' => '(053) 382-3294',
    ],
    [
        'name' => 'University of Eastern Philippines',
        'inst_type' => 'SUC Main',
        'city' => 'Catarman',
        'province' => 'Northern Samar',
        'region' => '08 - Eastern Visayas',
        'website' => 'uep.edu.ph',
        'email' => 'uepnsofficial@uep.edu.ph',
        'phone' => '(055) 251-8611',
    ],
    [
        'name' => 'Visayas State University',
        'inst_type' => 'SUC Main',
        'city' => 'Baybay City',
        'province' => 'Leyte',
        'region' => '08 - Eastern Visayas',
        'website' => 'www.vsu.edu.ph',
        'email' => 'information@vsu.edu.ph',
        'phone' => '(053) 563-7067',
    ],
    [
        'name' => 'Cavite State University-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Indang',
        'province' => 'Cavite',
        'region' => '04 - CALABARZON',
        'website' => 'www.cvsu.edu.ph',
        'email' => 'office.president@cvsu.edu.ph',
        'phone' => '(046) 415-0012; (046) 415-0010; (046) 415-0011',
    ],
    [
        'name' => 'Marinduque State University-Main Campus',
        'inst_type' => 'SUC Main',
        'city' => 'Boac',
        'province' => 'Marinduque',
        'region' => '04 - MIMAROPA',
        'website' => 'https://marinduquestatecollege.edu.ph',
        'email' => 'president@mscmarinduque.edu.ph',
        'phone' => '(042) 332-2028',
    ],
    [
        'name' => 'Western Philippines University',
        'inst_type' => 'SUC Main',
        'city' => 'Aborlan',
        'province' => 'Palawan',
        'region' => '04 - MIMAROPA',
        'website' => 'www.wpu.edu.ph',
        'email' => 'pres.office@wpu.edu.ph',
        'phone' => '(048) 433-4367; 0919-3836791; 0921-3769389; 0998-8686989',
    ],
    [
        'name' => 'Palawan State University',
        'inst_type' => 'SUC Main',
        'city' => 'Puerto Princesa City',
        'province' => 'Palawan',
        'region' => '04 - MIMAROPA',
        'website' => 'http://www.psu.palawan.edu.ph',
        'email' => 'rdocto@psu.palawan.edu.ph',
        'phone' => '(048) 433-5303; (048) 433-2379',
    ],
    [
        'name' => 'Romblon State University-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Odiongan',
        'province' => 'Romblon',
        'region' => '04 - MIMAROPA',
        'website' => 'www.rsu.edu.ph',
        'email' => 'romblonstateu@gmail.com',
        'phone' => '(042) 567-5271; (042) 567-5859; (042) 567-5273',
    ],
    [
        'name' => 'Aklan State University-Banga Campus',
        'inst_type' => 'SUC Main',
        'city' => 'Banga',
        'province' => 'Aklan',
        'region' => '06 - Western Visayas',
        'website' => 'www.asu.edu.ph',
        'email' => 'president@asu.edu.ph',
        'phone' => '(036) 267-5801',
    ],
    [
        'name' => 'Capiz State University-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Roxas City',
        'province' => 'Capiz',
        'region' => '06 - Western Visayas',
        'website' => 'www.capsu.edu.ph',
        'email' => 'admin@capsu.edu.ph',
        'phone' => '(036) 621-3514; (036) 621-4337; (036) 621-4311',
    ],
    [
        'name' => 'Guimaras State College-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Buenavista',
        'province' => 'Guimaras',
        'region' => '06 - Western Visayas',
        'website' => 'www1@gsc.edu.ph',
        'email' => 'university.president@gsu.edu.ph',
        'phone' => '(033) 580-8244; (033) 580-8245; (033) 580-8246',
    ],
    [
        'name' => 'Iloilo State College of Fisheries-Dingle and San Enrique Campus',
        'inst_type' => 'SUC Main',
        'city' => 'Barotac Nuevo',
        'province' => 'Iloilo',
        'region' => '06 - Western Visayas',
        'website' => 'http://www.iscof.edu.ph',
        'email' => 'iscofpresident@gmail.com',
        'phone' => '(033) 361-2369',
    ],
    [
        'name' => 'Northern Negros State College of Science and Technology',
        'inst_type' => 'SUC Main',
        'city' => 'Sagay City',
        'province' => 'Negros Occidental',
        'region' => '06 - Western Visayas',
        'website' => 'www.nonescost.edu.ph',
        'email' => 'ict@nonescost.edu.ph',
        'phone' => '(034) 722-4120',
    ],
    [
        'name' => 'Central Philippines State University-Main Campus',
        'inst_type' => 'SUC Main',
        'city' => 'Kabankalan City',
        'province' => 'Negros Occidental',
        'region' => '06 - Western Visayas',
        'website' => 'www.cpsu.edu.ph',
        'email' => 'officeofthepresident@cpsu.edu.ph',
        'phone' => '(034) 471-3045',
    ],
    [
        'name' => 'Northern Iloilo State University-Estancia, Iloilo',
        'inst_type' => 'SUC Main',
        'city' => 'Estancia',
        'province' => 'Iloilo',
        'region' => '06 - Western Visayas',
        'website' => 'www.nipsc.edu.ph',
        'email' => 'nisuadmin@nisu.edu.ph',
        'phone' => '(033) 397-0315; (033) 397-0314',
    ],
    [
        'name' => 'West Visayas State University-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Iloilo City',
        'province' => 'Iloilo',
        'region' => '06 - Western Visayas',
        'website' => 'http://www.wvsu.edu.ph',
        'email' => 'president@wvsu.edu.ph',
        'phone' => '(033) 320-0870 to77; (033) 320-0879; (033) 320-7793',
    ],
    [
        'name' => 'Iloilo Science and Technology University-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Iloilo City',
        'province' => 'Iloilo',
        'region' => '06 - Western Visayas',
        'website' => 'www.wvcst.edu.ph',
        'email' => 'mail@isatu.edu.ph',
        'phone' => '(033) 320-7190 loc 102; (033) 329-4274',
    ],
    [
        'name' => 'Camiguin Polytechnic State College',
        'inst_type' => 'SUC Main',
        'city' => 'Mambajao',
        'province' => 'Camiguin',
        'region' => '10 - Northern Mindanao',
        'website' => 'www.cpsc.edu.ph',
        'email' => 'president@cpsc.edu.ph',
        'phone' => '(088) 387-1268; (088) 387-0044; (088) 387-0495',
    ],
    [
        'name' => 'Central Mindanao University',
        'inst_type' => 'SUC Main',
        'city' => 'Maramag',
        'province' => 'Bukidnon',
        'region' => '10 - Northern Mindanao',
        'website' => 'www.cmu.edu.ph',
        'email' => 'cmu1910op@cmu.edu.ph',
        'phone' => '0917-7060347',
    ],
    [
        'name' => 'University of Science and Technology of Southern Philippines',
        'inst_type' => 'SUC Main',
        'city' => 'Cagayan De Oro City',
        'province' => 'Misamis Oriental',
        'region' => '10 - Northern Mindanao',
        'website' => 'http://www.ustp.edu.ph',
        'email' => 'president.office@ustp.edu.ph',
        'phone' => '(088) 856-4696; (088) 856-1739',
    ],
    [
        'name' => 'Northwestern Mindanao State College of Science and Technology',
        'inst_type' => 'SUC Main',
        'city' => 'Tangub City',
        'province' => 'Misamis Occidental',
        'region' => '10 - Northern Mindanao',
        'website' => 'www.nmsc.edu.ph',
        'email' => 'info@nmsc.edu.ph',
        'phone' => '(088) 586-0173',
    ],
    [
        'name' => 'Sultan Kudarat State University',
        'inst_type' => 'SUC Main',
        'city' => 'Tacurong City',
        'province' => 'Sultan Kudarat',
        'region' => '12 - Soccsksargen',
        'website' => 'www.sksu.edu.ph',
        'email' => 'ict@sksu.edu.ph',
        'phone' => '(064) 200-7336; 0917-7770754',
    ],
    [
        'name' => 'University of Southern Mindanao-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Kabacan',
        'province' => 'North Cotabato',
        'region' => '12 - Soccsksargen',
        'website' => 'www.usm.edu.ph',
        'email' => 'op@usm.edu.ph',
        'phone' => '(064) 248-2138; (064) 454-0175',
    ],
    [
        'name' => 'Abra State Institute of Science and Technology-Main',
        'inst_type' => 'SUC Main',
        'city' => 'Lagangilang',
        'province' => 'Abra',
        'region' => '14 - Cordillera Adm. Region',
        'website' => 'http://www.asist.edu.ph',
        'email' => 'president@asist.edu.ph',
        'phone' => '(074) 752-8171',
    ],
    [
        'name' => 'Benguet State University-Main',
        'inst_type' => 'SUC Main',
        'city' => 'La Trinidad',
        'province' => 'Benguet',
        'region' => '14 - Cordillera Adm. Region',
        'website' => 'www.bsu.edu.ph',
        'email' => 'president@bsu.edu.ph',
        'phone' => '(074) 422-2127; (074) 422-2009; (074) 422-2401',
    ],
    [
        'name' => 'Ifugao State University - Main',
        'inst_type' => 'SUC Main',
        'city' => 'Lamut',
        'province' => 'Ifugao',
        'region' => '14 - Cordillera Adm. Region',
        'website' => 'www.ifsu.edu.ph',
        'email' => 'ifsu.cedlamutcampus@gmail.com',
        'phone' => '0917-5742363',
    ],
    [
        'name' => 'Agusan Del Sur State College of Agriculture and Technology',
        'inst_type' => 'SUC Main',
        'city' => 'Bunawan',
        'province' => 'Agusan Del Sur',
        'region' => '16 - Caraga',
        'website' => 'http://asscat.edu.ph',
        'email' => 'op@asscat.edu.ph',
        'phone' => '0999-7490294',
    ],
    [
        'name' => 'Caraga State University-Main Campus',
        'inst_type' => 'SUC Main',
        'city' => 'Butuan City',
        'province' => 'Agusan Del Norte',
        'region' => '16 - Caraga',
        'website' => 'http://www.carsu.edu.ph',
        'email' => 'op@carsu.edu.ph',
        'phone' => '(085) 342-3047; (085) 342-1079; (085) 341-8677',
    ]
];
