import DtoAdditionalInfo from "@/Pages/Projects/BreedersMap/dto/DtoAdditionalInfo";
import ICommodityAdditionalInfo from "@/Pages/Projects/BreedersMap/interface/IAdditionalInfo";

export default class AdditionalInfo extends DtoAdditionalInfo {
    constructor(additionalInfo: ICommodityAdditionalInfo) {
        super(additionalInfo);
    }

    static getColumns() {
        return [
            {
                title: 'Commodity ID',
                key: 'commodity_id',
                db_key: 'commodity_id',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'NSIC Registration',
                key: 'nsicRegistration',
                db_key: 'nsicRegistration',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'NSIC Registration Number',
                key: 'nsicRegistrationNumber',
                db_key: 'nsicRegistrationNumber',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'NSIC Year Approved',
                key: 'nsicYearApproved',
                db_key: 'nsicYearApproved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'PVP Certificate Number',
                key: 'pvpCertificateNumber',
                db_key: 'pvpCertificateNumber',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'PVP Registration Year',
                key: 'pvpRegistrationYear',
                db_key: 'pvpRegistrationYear',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'NCBP Project Type',
                key: 'ncbpProjectType',
                db_key: 'ncbpProjectType',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'NCBP Status',
                key: 'ncbpStatus',
                db_key: 'ncbpStatus',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'NCBP Supervising IBC',
                key: 'ncbpSupervisingIbc',
                db_key: 'ncbpSupervisingIbc',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'NCBP Project Leaders',
                key: 'ncbpProjectLeaders',
                db_key: 'ncbpProjectLeaders',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'NCBP Date Approval',
                key: 'ncbpDateApproval',
                db_key: 'ncbpDateApproval',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'NCBP Date Completion',
                key: 'ncbpDateCompletion',
                db_key: 'ncbpDateCompletion',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Transformation Event',
                key: 'ao8TransformationEvent',
                db_key: 'ao8TransformationEvent',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Technology Developer',
                key: 'ao8TechnologyDeveloper',
                db_key: 'ao8TechnologyDeveloper',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Direct Use Status',
                key: 'ao8DirectUseStatus',
                db_key: 'ao8DirectUseStatus',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Direct Use Date Applied',
                key: 'ao8DirectUseDateApplied',
                db_key: 'ao8DirectUseDateApplied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Direct Use Date Approved',
                key: 'ao8DirectUseDateApproved',
                db_key: 'ao8DirectUseDateApproved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Field Trial Status',
                key: 'ao8FieldTrialStatus',
                db_key: 'ao8FieldTrialStatus',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Field Trial Date Applied',
                key: 'ao8FieldTrialDateApplied',
                db_key: 'ao8FieldTrialDateApplied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Field Trial Date Approved',
                key: 'ao8FieldTrialDateApproved',
                db_key: 'ao8FieldTrialDateApproved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Propagation Status',
                key: 'ao8PropagationStatus',
                db_key: 'ao8PropagationStatus',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Propagation Date Applied',
                key: 'ao8PropagationDateApplied',
                db_key: 'ao8PropagationDateApplied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Propagation Date Approved',
                key: 'ao8PropagationDateApproved',
                db_key: 'ao8PropagationDateApproved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Transformation Event',
                key: 'jdc2016TransformationEvent',
                db_key: 'jdc2016TransformationEvent',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Technology Developer',
                key: 'jdc2016TechnologyDeveloper',
                db_key: 'jdc2016TechnologyDeveloper',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Direct Use Status',
                key: 'jdc2016DirectUseStatus',
                db_key: 'jdc2016DirectUseStatus',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Direct Use Date Applied',
                key: 'jdc2016DirectUseDateApplied',
                db_key: 'jdc2016DirectUseDateApplied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Direct Use Date Approved',
                key: 'jdc2016DirectUseDateApproved',
                db_key: 'jdc2016DirectUseDateApproved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 FFP Status',
                key: 'jdc2016FfpStatus',
                db_key: 'jdc2016FfpStatus',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 FFP Date Applied',
                key: 'jdc2016FfpDateApplied',
                db_key: 'jdc2016FfpDateApplied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 FFP Date Approved',
                key: 'jdc2016FfpDateApproved',
                db_key: 'jdc2016FfpDateApproved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Field Trial Status',
                key: 'jdc2016FieldTrialStatus',
                db_key: 'jdc2016FieldTrialStatus',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Field Trial Date Applied',
                key: 'jdc2016FieldTrialDateApplied',
                db_key: 'jdc2016FieldTrialDateApplied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Field Trial Date Approved',
                key: 'jdc2016FieldTrialDateApproved',
                db_key: 'jdc2016FieldTrialDateApproved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Propagation Status',
                key: 'jdc2016PropagationStatus',
                db_key: 'jdc2016PropagationStatus',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Propagation Date Applied',
                key: 'jdc2016PropagationDateApplied',
                db_key: 'jdc2016PropagationDateApplied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Propagation Date Approved',
                key: 'jdc2016PropagationDateApproved',
                db_key: 'jdc2016PropagationDateApproved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Renewal Propagation Status',
                key: 'jdc2016RenewalPropagationStatus',
                db_key: 'jdc2016RenewalPropagationStatus',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Renewal Propagation Date Applied',
                key: 'jdc2016RenewalPropagationDateApplied',
                db_key: 'jdc2016RenewalPropagationDateApplied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Renewal Propagation Date Approved',
                key: 'jdc2016RenewalPropagationDateApproved',
                db_key: 'jdc2016RenewalPropagationDateApproved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Deregulation Status',
                key: 'jdc2016DeregulationStatus',
                db_key: 'jdc2016DeregulationStatus',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Deregulation Date Applied',
                key: 'jdc2016DeregulationDateApplied',
                db_key: 'jdc2016DeregulationDateApplied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Deregulation Date Approved',
                key: 'jdc2016DeregulationDateApproved',
                db_key: 'jdc2016DeregulationDateApproved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Transformation Event',
                key: 'jdc2021TransformationEvent',
                db_key: 'jdc2021TransformationEvent',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Technology Developer',
                key: 'jdc2021TechnologyDeveloper',
                db_key: 'jdc2021TechnologyDeveloper',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Direct Use Status',
                key: 'jdc2021DirectUseStatus',
                db_key: 'jdc2021DirectUseStatus',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Direct Use Date Applied',
                key: 'jdc2021DirectUseDateApplied',
                db_key: 'jdc2021DirectUseDateApplied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Direct Use Date Approved',
                key: 'jdc2021DirectUseDateApproved',
                db_key: 'jdc2021DirectUseDateApproved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Field Trial Status',
                key: 'jdc2021FieldTrialStatus',
                db_key: 'jdc2021FieldTrialStatus',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Field Trial Date Applied',
                key: 'jdc2021FieldTrialDateApplied',
                db_key: 'jdc2021FieldTrialDateApplied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Field Trial Date Approved',
                key: 'jdc2021FieldTrialDateApproved',
                db_key: 'jdc2021FieldTrialDateApproved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Propagation Status',
                key: 'jdc2021PropagationStatus',
                db_key: 'jdc2021PropagationStatus',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Propagation Date Applied',
                key: 'jdc2021PropagationDateApplied',
                db_key: 'jdc2021PropagationDateApplied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Propagation Date Approved',
                key: 'jdc2021PropagationDateApproved',
                db_key: 'jdc2021PropagationDateApproved',
                sortable: true,
                align: 'center',
                visible: true,
            },
        ];
    }
}
