import DtoAdditionalInfo from "@/Pages/Projects/BreedersMap/dto/DtoAdditionalInfo";
import IAdditionalInfo from "@/Pages/Projects/BreedersMap/interface/IAdditionalInfo";

export default class AdditionalInfo extends DtoAdditionalInfo {
    constructor(additionalInfo: IAdditionalInfo) {
        super(additionalInfo);
    }

    static getColumns() {
        return [
            {
                title: 'Commodity ID',
                key: 'commodity_id',
                db_key: 'commodity_id',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'NSIC Registration',
                key: 'nsic_registration',
                db_key: 'nsic_registration',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'NSIC Registration Number',
                key: 'nsic_registration_number',
                db_key: 'nsic_registration_number',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'NSIC Year Approved',
                key: 'nsic_year_approved',
                db_key: 'nsic_year_approved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'PVP Certificate Number',
                key: 'pvp_certificate_number',
                db_key: 'pvp_certificate_number',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'PVP Registration Year',
                key: 'pvp_registration_year',
                db_key: 'pvp_registration_year',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'NCBP Project Type',
                key: 'ncbp_project_type',
                db_key: 'ncbp_project_type',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'NCBP Status',
                key: 'ncbp_status',
                db_key: 'ncbp_status',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'NCBP Supervising IBC',
                key: 'ncbp_supervising_ibc',
                db_key: 'ncbp_supervising_ibc',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'NCBP Project Leaders',
                key: 'ncbp_project_leaders',
                db_key: 'ncbp_project_leaders',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'NCBP Date Approval',
                key: 'ncbp_date_approval',
                db_key: 'ncbp_date_approval',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'NCBP Date Completion',
                key: 'ncbp_date_completion',
                db_key: 'ncbp_date_completion',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Transformation Event',
                key: 'ao8_transformation_event',
                db_key: 'ao8_transformation_event',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Technology Developer',
                key: 'ao8_technology_developer',
                db_key: 'ao8_technology_developer',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Direct Use Status',
                key: 'ao8_direct_use_status',
                db_key: 'ao8_direct_use_status',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Direct Use Date Applied',
                key: 'ao8_direct_use_date_applied',
                db_key: 'ao8_direct_use_date_applied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Direct Use Date Approved',
                key: 'ao8_direct_use_date_approved',
                db_key: 'ao8_direct_use_date_approved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Field Trial Status',
                key: 'ao8_field_trial_status',
                db_key: 'ao8_field_trial_status',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Field Trial Date Applied',
                key: 'ao8_field_trial_date_applied',
                db_key: 'ao8_field_trial_date_applied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Field Trial Date Approved',
                key: 'ao8_field_trial_date_approved',
                db_key: 'ao8_field_trial_date_approved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Propagation Status',
                key: 'ao8_propagation_status',
                db_key: 'ao8_propagation_status',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Propagation Date Applied',
                key: 'ao8_propagation_date_applied',
                db_key: 'ao8_propagation_date_applied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'AO8 Propagation Date Approved',
                key: 'ao8_propagation_date_approved',
                db_key: 'ao8_propagation_date_approved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Transformation Event',
                key: 'jdc_2016_transformation_event',
                db_key: 'jdc_2016_transformation_event',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Technology Developer',
                key: 'jdc_2016_technology_developer',
                db_key: 'jdc_2016_technology_developer',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Direct Use Status',
                key: 'jdc_2016_direct_use_status',
                db_key: 'jdc_2016_direct_use_status',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Direct Use Date Applied',
                key: 'jdc_2016_direct_use_date_applied',
                db_key: 'jdc_2016_direct_use_date_applied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Direct Use Date Approved',
                key: 'jdc_2016_direct_use_date_approved',
                db_key: 'jdc_2016_direct_use_date_approved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 FFP Status',
                key: 'jdc_2016_ffp_status',
                db_key: 'jdc_2016_ffp_status',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 FFP Date Applied',
                key: 'jdc_2016_ffp_date_applied',
                db_key: 'jdc_2016_ffp_date_applied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 FFP Date Approved',
                key: 'jdc_2016_ffp_date_approved',
                db_key: 'jdc_2016_ffp_date_approved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Field Trial Status',
                key: 'jdc_2016_field_trial_status',
                db_key: 'jdc_2016_field_trial_status',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Field Trial Date Applied',
                key: 'jdc_2016_field_trial_date_applied',
                db_key: 'jdc_2016_field_trial_date_applied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Field Trial Date Approved',
                key: 'jdc_2016_field_trial_date_approved',
                db_key: 'jdc_2016_field_trial_date_approved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Propagation Status',
                key: 'jdc_2016_propagation_status',
                db_key: 'jdc_2016_propagation_status',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Propagation Date Applied',
                key: 'jdc_2016_propagation_date_applied',
                db_key: 'jdc_2016_propagation_date_applied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Propagation Date Approved',
                key: 'jdc_2016_propagation_date_approved',
                db_key: 'jdc_2016_propagation_date_approved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Renewal Propagation Status',
                key: 'jdc_2016_renewal_propagation_status',
                db_key: 'jdc_2016_renewal_propagation_status',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Renewal Propagation Date Applied',
                key: 'jdc_2016_renewal_propagation_date_applied',
                db_key: 'jdc_2016_renewal_propagation_date_applied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Renewal Propagation Date Approved',
                key: 'jdc_2016_renewal_propagation_date_approved',
                db_key: 'jdc_2016_renewal_propagation_date_approved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Deregulation Status',
                key: 'jdc_2016_deregulation_status',
                db_key: 'jdc_2016_deregulation_status',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Deregulation Date Applied',
                key: 'jdc_2016_deregulation_date_applied',
                db_key: 'jdc_2016_deregulation_date_applied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2016 Deregulation Date Approved',
                key: 'jdc_2016_deregulation_date_approved',
                db_key: 'jdc_2016_deregulation_date_approved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Transformation Event',
                key: 'jdc_2021_transformation_event',
                db_key: 'jdc_2021_transformation_event',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Technology Developer',
                key: 'jdc_2021_technology_developer',
                db_key: 'jdc_2021_technology_developer',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Direct Use Status',
                key: 'jdc_2021_direct_use_status',
                db_key: 'jdc_2021_direct_use_status',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Direct Use Date Applied',
                key: 'jdc_2021_direct_use_date_applied',
                db_key: 'jdc_2021_direct_use_date_applied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Direct Use Date Approved',
                key: 'jdc_2021_direct_use_date_approved',
                db_key: 'jdc_2021_direct_use_date_approved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Field Trial Status',
                key: 'jdc_2021_field_trial_status',
                db_key: 'jdc_2021_field_trial_status',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Field Trial Date Applied',
                key: 'jdc_2021_field_trial_date_applied',
                db_key: 'jdc_2021_field_trial_date_applied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Field Trial Date Approved',
                key: 'jdc_2021_field_trial_date_approved',
                db_key: 'jdc_2021_field_trial_date_approved',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Propagation Status',
                key: 'jdc_2021_propagation_status',
                db_key: 'jdc_2021_propagation_status',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Propagation Date Applied',
                key: 'jdc_2021_propagation_date_applied',
                db_key: 'jdc_2021_propagation_date_applied',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'JDC 2021 Propagation Date Approved',
                key: 'jdc_2021_propagation_date_approved',
                db_key: 'jdc_2021_propagation_date_approved',
                sortable: true,
                align: 'center',
                visible: true,
            },
        ];
    }
}
