import DtoCommodity from "../dto/DtoCommodity";

export default class Commodity extends DtoCommodity {
    constructor(params: DtoCommodity) {
        // @ts-ignore
        super(params);

        this.indexUri = 'api.commodities.index';
        this.showUri = 'api.commodities.show';
        this.storeUri = 'api.commodities.store';
        this.updateUri = 'api.commodities.update';
        this.destroyUri = 'api.commodities.destroy';
        this.multiDestroyUri = 'api.commodities.destroy.multi';
        this.summaryUri = 'api.commodities.summary';

        this.appendWith = ['breeder', 'location', 'characteristics', 'additionalinfo'];
    }

    static createForm()
    {
        return {
            user_id: null,
            breeder_id: null,
            name: '',
            scientific_name: '',
            variety: '',
            accession: '',
            germplasm: '',
            population: '',
            maturity_period: '',
            yield: '',
            description: '',
            status: '',
            geolocation: '',

            weight: '',
            length: '',
            width: '',
            shape: '',

            skin_color: '',
            skin_texture: '',
            flesh_color: '',
            flesh_texture: '',
            flesh_flavor: '',
            aroma: '',

            root_flesh_color: '',
            root_cortex_color: '',
            root_skin_color: '',
            root_shape: '',

            tuber_flesh_color: '',
            tuber_cortex_color: '',
            tuber_skin_color: '',
            tuber_shape: '',

            nsic_registration: '',
            nsic_registration_number: '',
            nsic_year_approved: '',

            pvp_certificate_number: '',
            pvp_registration_year: '',

            ncbp_project_type: '',
            ncbp_status: '',
            ncbp_supervising_ibc: '',
            ncbp_project_leaders: '',
            ncbp_date_approval: '',
            ncbp_date_completion: '',

            ao8_transformation_event: '',
            ao8_technology_developer: '',
            ao8_direct_use_status: '',
            ao8_direct_use_date_applied: '',
            ao8_direct_use_date_approved: '',
            ao8_field_trial_status: '',
            ao8_field_trial_date_applied: '',
            ao8_field_trial_date_approved: '',
            ao8_propagation_status: '',
            ao8_propagation_date_applied: '',
            ao8_propagation_date_approved: '',

            jdc_2016_transformation_event: '',
            jdc_2016_technology_developer: '',
            jdc_2016_direct_use_status: '',
            jdc_2016_direct_use_date_applied: '',
            jdc_2016_direct_use_date_approved: '',
            jdc_2016_ffp_status: '',
            jdc_2016_ffp_date_applied: '',
            jdc_2016_ffp_date_approved: '',
            jdc_2016_field_trial_status: '',
            jdc_2016_field_trial_date_applied: '',
            jdc_2016_field_trial_date_approved: '',
            jdc_2016_propagation_status: '',
            jdc_2016_propagation_date_applied: '',
            jdc_2016_propagation_date_approved: '',
            jdc_2016_renewal_propagation_status: '',
            jdc_2016_renewal_propagation_date_applied: '',
            jdc_2016_renewal_propagation_date_approved: '',
            jdc_2016_deregulation_status: '',
            jdc_2016_deregulation_date_applied: '',
            jdc_2016_deregulation_date_approved: '',

            jdc_2021_transformation_event: '',
            jdc_2021_technology_developer: '',
            jdc_2021_direct_use_status: '',
            jdc_2021_direct_use_date_applied: '',
            jdc_2021_direct_use_date_approved: '',
            jdc_2021_field_trial_status: '',
            jdc_2021_field_trial_date_applied: '',
            jdc_2021_field_trial_date_approved: '',
            jdc_2021_propagation_status: '',
            jdc_2021_propagation_date_applied: '',
            jdc_2021_propagation_date_approved: '',
        };
    }

    static updateForm(oldValue: Partial<Commodity>)
    {
        return {
            id: oldValue.id ?? null,
            breeder_id: oldValue.breeder_id ?? null,
            name: oldValue.name ?? '',
            scientific_name: oldValue.scientific_name ?? '',
            variety: oldValue.variety ?? '',
            accession: oldValue.accession ?? '',
            germplasm: oldValue.germplasm ?? '',
            population: oldValue.population ?? '',
            maturity_period: oldValue.maturity_period ?? '',
            yield: oldValue.yield ?? '',
            description: oldValue.description ?? '',
            status: oldValue.status ?? '',
            geolocation: oldValue.location ? oldValue.location.id : '',

            weight: oldValue.characteristics?.weight ?? '',
            length: oldValue.characteristics?.length ?? '',
            width: oldValue.characteristics?.width ?? '',
            shape: oldValue.characteristics?.shape ?? '',

            skin_color: oldValue.characteristics?.skin_color ?? '',
            skin_texture: oldValue.characteristics?.skin_texture ?? '',
            flesh_color: oldValue.characteristics?.flesh_color ?? '',
            flesh_texture: oldValue.characteristics?.flesh_texture ?? '',
            flesh_flavor: oldValue.characteristics?.flesh_flavor ?? '',
            aroma: oldValue.characteristics?.aroma ?? '',

            root_flesh_color: oldValue.characteristics?.root_flesh_color ?? '',
            root_cortex_color: oldValue.characteristics?.root_cortex_color ?? '',
            root_skin_color: oldValue.characteristics?.root_skin_color ?? '',
            root_shape: oldValue.characteristics?.root_shape ?? '',
            tuber_flesh_color: oldValue.characteristics?.tuber_flesh_color ?? '',
            tuber_cortex_color: oldValue.characteristics?.tuber_cortex_color ?? '',
            tuber_skin_color: oldValue.characteristics?.tuber_skin_color ?? '',
            tuber_shape: oldValue.characteristics?.tuber_shape ?? '',

            nsic_registration: oldValue.additionalinfo?.nsic_registration ?? '',
            nsic_registration_number: oldValue.additionalinfo?.nsic_registration_number ?? '',
            nsic_year_approved: oldValue.additionalinfo?.nsic_year_approved ?? '',
            pvp_certificate_number: oldValue.additionalinfo?.pvp_certificate_number ?? '',
            pvp_registration_year: oldValue.additionalinfo?.pvp_registration_year ?? '',

            ncbp_project_type: oldValue.additionalinfo?.ncbp_project_type ?? '',
            ncbp_status: oldValue.additionalinfo?.ncbp_status ?? '',
            ncbp_supervising_ibc: oldValue.additionalinfo?.ncbp_supervising_ibc ?? '',
            ncbp_project_leaders: oldValue.additionalinfo?.ncbp_project_leaders ?? '',
            ncbp_date_approval: oldValue.additionalinfo?.ncbp_date_approval ?? '',
            ncbp_date_completion: oldValue.additionalinfo?.ncbp_date_completion ?? '',

            ao8_transformation_event: oldValue.additionalinfo?.ao8_transformation_event ?? '',
            ao8_technology_developer: oldValue.additionalinfo?.ao8_technology_developer ?? '',
            ao8_direct_use_status: oldValue.additionalinfo?.ao8_direct_use_status ?? '',
            ao8_direct_use_date_applied: oldValue.additionalinfo?.ao8_direct_use_date_applied ?? '',
            ao8_direct_use_date_approved: oldValue.additionalinfo?.ao8_direct_use_date_approved ?? '',
            ao8_field_trial_status: oldValue.additionalinfo?.ao8_field_trial_status ?? '',
            ao8_field_trial_date_applied: oldValue.additionalinfo?.ao8_field_trial_date_applied ?? '',
            ao8_field_trial_date_approved: oldValue.additionalinfo?.ao8_field_trial_date_approved ?? '',
            ao8_propagation_status: oldValue.additionalinfo?.ao8_propagation_status ?? '',
            ao8_propagation_date_applied: oldValue.additionalinfo?.ao8_propagation_date_applied ?? '',
            ao8_propagation_date_approved: oldValue.additionalinfo?.ao8_propagation_date_approved ?? '',

            jdc_2016_transformation_event: oldValue.additionalinfo?.jdc_2016_transformation_event ?? '',
            jdc_2016_technology_developer: oldValue.additionalinfo?.jdc_2016_technology_developer ?? '',
            jdc_2016_direct_use_status: oldValue.additionalinfo?.jdc_2016_direct_use_status ?? '',
            jdc_2016_direct_use_date_applied: oldValue.additionalinfo?.jdc_2016_direct_use_date_applied ?? '',
            jdc_2016_direct_use_date_approved: oldValue.additionalinfo?.jdc_2016_direct_use_date_approved ?? '',
            jdc_2016_ffp_status: oldValue.additionalinfo?.jdc_2016_ffp_status ?? '',
            jdc_2016_ffp_date_applied: oldValue.additionalinfo?.jdc_2016_ffp_date_applied ?? '',
            jdc_2016_ffp_date_approved: oldValue.additionalinfo?.jdc_2016_ffp_date_approved ?? '',
            jdc_2016_field_trial_status: oldValue.additionalinfo?.jdc_2016_field_trial_status ?? '',
            jdc_2016_field_trial_date_applied: oldValue.additionalinfo?.jdc_2016_field_trial_date_applied ?? '',
            jdc_2016_field_trial_date_approved: oldValue.additionalinfo?.jdc_2016_field_trial_date_approved ?? '',
            jdc_2016_propagation_status: oldValue.additionalinfo?.jdc_2016_propagation_status ?? '',
            jdc_2016_propagation_date_applied: oldValue.additionalinfo?.jdc_2016_propagation_date_applied ?? '',
            jdc_2016_propagation_date_approved: oldValue.additionalinfo?.jdc_2016_propagation_date_approved ?? '',
            jdc_2016_renewal_propagation_status: oldValue.additionalinfo?.jdc_2016_renewal_propagation_status ?? '',
            jdc_2016_renewal_propagation_date_applied: oldValue.additionalinfo?.jdc_2016_renewal_propagation_date_applied ?? '',
            jdc_2016_renewal_propagation_date_approved: oldValue.additionalinfo?.jdc_2016_renewal_propagation_date_approved ?? '',
            jdc_2016_deregulation_status: oldValue.additionalinfo?.jdc_2016_deregulation_status ?? '',
            jdc_2016_deregulation_date_applied: oldValue.additionalinfo?.jdc_2016_deregulation_date_applied ?? '',
            jdc_2016_deregulation_date_approved: oldValue.additionalinfo?.jdc_2016_deregulation_date_approved ?? '',
            jdc_2021_transformation_event: oldValue.additionalinfo?.jdc_2021_transformation_event ?? '',
            jdc_2021_technology_developer: oldValue.additionalinfo?.jdc_2021_technology_developer ?? '',
            jdc_2021_direct_use_status: oldValue.additionalinfo?.jdc_2021_direct_use_status ?? '',
            jdc_2021_direct_use_date_applied: oldValue.additionalinfo?.jdc_2021_direct_use_date_applied ?? '',
            jdc_2021_direct_use_date_approved: oldValue.additionalinfo?.jdc_2021_direct_use_date_approved ?? '',
            jdc_2021_field_trial_status: oldValue.additionalinfo?.jdc_2021_field_trial_status ?? '',
            jdc_2021_field_trial_date_applied: oldValue.additionalinfo?.jdc_2021_field_trial_date_applied ?? '',
            jdc_2021_field_trial_date_approved: oldValue.additionalinfo?.jdc_2021_field_trial_date_approved ?? '',
            jdc_2021_propagation_status: oldValue.additionalinfo?.jdc_2021_propagation_status ?? '',
            jdc_2021_propagation_date_applied: oldValue.additionalinfo?.jdc_2021_propagation_date_applied ?? '',
            jdc_2021_propagation_date_approved: oldValue.additionalinfo?.jdc_2021_propagation_date_approved ?? '',
        };
    }

    static getCardColumns() {
        return [
            {
                title: 'ID',
                key: 'id',
                align: 'center',
                visible: false,
            },
            {
                title: 'User ID',
                key: 'user_id',
                align: 'center',
                visible: false,
            },
            {
                title: 'Breeder ID',
                key: 'breeder_id',
                align: 'center',
                visible: false,
            },
            {
                title: 'Breeder',
                key: 'breederName',
                align: 'center',
                visible: true,
            },
            {
                title: 'Affiliation',
                key: 'breederAffiliation',
                align: 'center',
                visible: true,
            },
            {
                title: 'Email',
                key: 'breederEmail',
                align: 'center',
                visible: false,
            },
            {
                title: 'Contact #',
                key: 'breederMobileNo',
                align: 'center',
                visible: true,
            },
            {
                title: 'Commodity',
                key: 'name',
                align: 'center',
                visible: true,
            },
            {
                title: 'Scientific Name',
                key: 'scientific_name',
                align: 'center italic',
                visible: true,
            },
            {
                title: 'Variety',
                key: 'variety',
                align: 'center',
                visible: false,
            },
            {
                title: 'Accession',
                key: 'accession',
                align: 'center',
                visible: false,
            },
            {
                title: 'Germplasm',
                key: 'germplasm',
                align: 'center',
                visible: false,
            },
            {
                title: 'Population',
                key: 'population',
                align: 'center',
                visible: false,
            },
            {
                title: 'Maturity Period',
                key: 'maturity_period',
                align: 'center',
                visible: false,
            },
            {
                title: 'Yield',
                key: 'yield',
                align: 'center',
                visible: false,
            },
            {
                title: 'Description',
                key: 'description',
                align: 'center',
                visible: false,
            },
            {
                title: 'Status',
                key: 'status',
                align: 'center',
                visible: false,
            },
            {
                title: 'Location',
                key: 'location.getFullAddress',
                align: 'center',
                visible: true,
            },
            {
                title: 'Updated At',
                key: 'updated_at',
                align: 'center',
                visible: false,
            },
            {
                title: 'Created At',
                key: 'created_at',
                align: 'center',
                visible: false,
            },
            {
                title: 'Deleted At',
                key: 'deleted_at',
                align: 'center',
                visible: false,
            },
            {
                title: 'Characteristics',
                key: 'characteristics',
                align: 'center',
                visible: false,
            },
            {
                title: 'Additional Info',
                key: 'additionalinfo',
                align: 'center',
                visible: false,
            },
        ]
    }

    static getColumns(){
        return [
            {
                title: 'ID',
                key: 'id',
                db_key: 'id',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'User ID',
                key: 'user_id',
                db_key: 'user_id',
                align: 'center',
                sortable: true,
                visible: false,
            },
            {
                title: 'Breeder ID',
                key: 'breeder_id',
                db_key: 'breeder_id',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'Breeder',
                key: 'breeder.getFullName',
                db_key: 'breeder.name',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'Commodity',
                key: 'name',
                db_key: 'name',
                keyLabel: 'Commodity',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'Scientific Name',
                key: 'scientific_name',
                db_key: 'scientific_name',
                sortable: true,
                align: 'center italic',
                visible: true,
            },
            {
                title: 'Variety',
                key: 'variety',
                db_key: 'variety',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'Accession',
                key: 'accession',
                db_key: 'accession',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'Germplasm',
                key: 'germplasm',
                db_key: 'germplasm',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'Population',
                key: 'population',
                db_key: 'population',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'Maturity Period',
                key: 'maturity_period',
                db_key: 'maturity_period',
                sortable: false,
                align: 'center',
                visible: true,
            },
            {
                title: 'Yield',
                key: 'yield',
                db_key: 'yield',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'Description',
                key: 'description',
                db_key: 'description',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'Status',
                key: 'status',
                db_key: 'status',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'Location',
                key: 'location.getFullAddress',
                db_key: 'location',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'Updated At',
                key: 'updated_at',
                db_key: 'updated_at',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'Created At',
                key: 'created_at',
                db_key: 'created_at',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'Deleted At',
                key: 'deleted_at',
                db_key: 'deleted_at',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'Characteristics',
                key: 'characteristics',
                db_key: 'characteristics',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'Additional Info',
                key: 'additionalinfo',
                db_key: 'additionalinfo',
                sortable: true,
                align: 'center',
                visible: false,
            },
        ];
    }
}
