import DtoCommodity from "../dto/DtoCommodity";

export default class Commodity extends DtoCommodity {
    constructor(params: DtoCommodity) {
        // @ts-ignore
        super(params);

        this.indexUri = 'api.commodities.index';
        this.showUri = 'api.commodities.show';
        this.storeUri = 'api.commodities.store';
        this.updateUri = 'api.commodities.update';
        this.destroyUri = 'api.commodities.destroy';
        this.multiDestroyUri = 'api.commodities.destroy.multi';
        this.summaryUri = 'api.commodities.summary';

        this.appendWith = ['breeder', 'location', 'characteristics', 'additionalinfo'];
    }

    static getCreateFieldTitles() {
        return {
            user_id: 'Enter the name of the data encoder',
            breeder_id: 'Select the plant breeder',
            name: 'Select a commodity name',
            scientific_name: 'Enter the scientific name (if applicable)',
            variety: 'Specify the variety name',
            accession: 'Enter the accession number',
            population: 'Enter the population size (if applicable)',
            maturity_period: 'Enter the maturity period (e.g., days to harvest)',
            yield: 'Specify the expected yield (e.g., tons per hectare)',
            description: 'Provide additional details or remarks',
            photo: '5mb max file size',
            geolocation: 'Enter the location coordinates or region',

            weight: 'Enter the average weight (in grams or kilograms)',
            length: 'Specify the length (in cm)',
            width: 'Specify the width (in cm)',
            shape: 'Describe the shape',

            skin_color: 'Describe the skin color',
            skin_texture: 'Describe the skin texture',
            flesh_color: 'Specify the flesh color',
            flesh_texture: 'Describe the flesh texture',
            flesh_flavor: 'Describe the flavor profile',
            aroma: 'Describe the aroma (if applicable)',

            root_flesh_color: 'Specify the root flesh color',
            root_cortex_color: 'Specify the root cortex color',
            root_skin_color: 'Specify the root skin color',
            root_shape: 'Describe the root shape',

            tuber_flesh_color: 'Specify the tuber flesh color',
            tuber_cortex_color: 'Specify the tuber cortex color',
            tuber_skin_color: 'Specify the tuber skin color',
            tuber_shape: 'Describe the tuber shape',

            nsic_registration: 'Indicate if NSIC registration is available',
            nsic_registration_number: 'Enter the NSIC registration number',
            nsic_year_approved: 'Enter the year of NSIC approval',

            pvp_certificate_number: 'Enter the PVP certificate number',
            pvp_registration_year: 'Enter the year of PVP registration',

            ncbp_project_type: 'Select the NCBP project type',
            ncbp_status: 'Indicate the NCBP approval status',
            ncbp_supervising_ibc: 'Enter the supervising IBC',
            ncbp_project_leaders: 'List the project leaders',
            ncbp_date_approval: 'Enter the date of NCBP approval',
            ncbp_date_completion: 'Enter the expected completion date',

            ao8_transformation_event: 'Enter the AO8 transformation event',
            ao8_technology_developer: 'Enter the name of the technology developer',
            ao8_direct_use_status: 'Indicate the direct use approval status',
            ao8_direct_use_date_applied: 'Enter the date applied for direct use',
            ao8_direct_use_date_approved: 'Enter the date approved for direct use',
            ao8_field_trial_status: 'Indicate the field trial approval status',
            ao8_field_trial_date_applied: 'Enter the date applied for field trial',
            ao8_field_trial_date_approved: 'Enter the date approved for field trial',
            ao8_propagation_status: 'Indicate the propagation approval status',
            ao8_propagation_date_applied: 'Enter the date applied for propagation',
            ao8_propagation_date_approved: 'Enter the date approved for propagation',

            jdc_2016_transformation_event: 'Enter the JDC 2016 transformation event',
            jdc_2016_technology_developer: 'Enter the JDC 2016 technology developer',
            jdc_2016_direct_use_status: 'Indicate JDC 2016 direct use status',
            jdc_2016_direct_use_date_applied: 'Enter the JDC 2016 direct use date applied',
            jdc_2016_direct_use_date_approved: 'Enter the JDC 2016 direct use date approved',
            jdc_2016_ffp_status: 'Indicate JDC 2016 FFP status',
            jdc_2016_ffp_date_applied: 'Enter the JDC 2016 FFP date applied',
            jdc_2016_ffp_date_approved: 'Enter the JDC 2016 FFP date approved',
            jdc_2016_field_trial_status: 'Indicate JDC 2016 field trial status',
            jdc_2016_field_trial_date_applied: 'Enter the JDC 2016 field trial date applied',
            jdc_2016_field_trial_date_approved: 'Enter the JDC 2016 field trial date approved',
            jdc_2016_propagation_status: 'Indicate JDC 2016 propagation status',
            jdc_2016_propagation_date_applied: 'Enter the JDC 2016 propagation date applied',
            jdc_2016_propagation_date_approved: 'Enter the JDC 2016 propagation date approved',
            jdc_2016_renewal_propagation_status: 'Indicate JDC 2016 renewal propagation status',
            jdc_2016_renewal_propagation_date_applied: 'Enter the JDC 2016 renewal propagation date applied',
            jdc_2016_renewal_propagation_date_approved: 'Enter the JDC 2016 renewal propagation date approved',
            jdc_2016_deregulation_status: 'Indicate JDC 2016 deregulation status',
            jdc_2016_deregulation_date_applied: 'Enter the JDC 2016 deregulation date applied',
            jdc_2016_deregulation_date_approved: 'Enter the JDC 2016 deregulation date approved',

            jdc_2021_transformation_event: 'Enter the JDC 2021 transformation event',
            jdc_2021_technology_developer: 'Enter the JDC 2021 technology developer',
            jdc_2021_direct_use_status: 'Indicate JDC 2021 direct use status',
            jdc_2021_direct_use_date_applied: 'Enter the JDC 2021 direct use date applied',
            jdc_2021_direct_use_date_approved: 'Enter the JDC 2021 direct use date approved',
            jdc_2021_field_trial_status: 'Indicate JDC 2021 field trial status',
            jdc_2021_field_trial_date_applied: 'Enter the JDC 2021 field trial date applied',
            jdc_2021_field_trial_date_approved: 'Enter the JDC 2021 field trial date approved',
            jdc_2021_propagation_status: 'Indicate JDC 2021 propagation status',
            jdc_2021_propagation_date_applied: 'Enter the JDC 2021 propagation date applied',
            jdc_2021_propagation_date_approved: 'Enter the JDC 2021 propagation date approved',
        };
    }

    static getUpdateFieldTitles() {
        return this.getCreateFieldTitles();
    }

    static createForm()
    {
        return {
            user_id: null,
            breeder_id: null,
            name: '',
            scientific_name: '',
            variety: '',
            accession: '',
            population: '',
            maturity_period: '',
            yield: '',
            description: '',
            photo: '',
            geolocation: '',

            weight: '',
            length: '',
            width: '',
            shape: '',

            skin_color: '',
            skin_texture: '',
            flesh_color: '',
            flesh_texture: '',
            flesh_flavor: '',
            aroma: '',

            root_flesh_color: '',
            root_cortex_color: '',
            root_skin_color: '',
            root_shape: '',

            tuber_flesh_color: '',
            tuber_cortex_color: '',
            tuber_skin_color: '',
            tuber_shape: '',

            nsic_registration: '',
            nsic_registration_number: '',
            nsic_year_approved: '',

            pvp_certificate_number: '',
            pvp_registration_year: '',

            ncbp_project_type: '',
            ncbp_status: '',
            ncbp_supervising_ibc: '',
            ncbp_project_leaders: '',
            ncbp_date_approval: '',
            ncbp_date_completion: '',

            ao8_transformation_event: '',
            ao8_technology_developer: '',
            ao8_direct_use_status: '',
            ao8_direct_use_date_applied: '',
            ao8_direct_use_date_approved: '',
            ao8_field_trial_status: '',
            ao8_field_trial_date_applied: '',
            ao8_field_trial_date_approved: '',
            ao8_propagation_status: '',
            ao8_propagation_date_applied: '',
            ao8_propagation_date_approved: '',

            jdc_2016_transformation_event: '',
            jdc_2016_technology_developer: '',
            jdc_2016_direct_use_status: '',
            jdc_2016_direct_use_date_applied: '',
            jdc_2016_direct_use_date_approved: '',
            jdc_2016_ffp_status: '',
            jdc_2016_ffp_date_applied: '',
            jdc_2016_ffp_date_approved: '',
            jdc_2016_field_trial_status: '',
            jdc_2016_field_trial_date_applied: '',
            jdc_2016_field_trial_date_approved: '',
            jdc_2016_propagation_status: '',
            jdc_2016_propagation_date_applied: '',
            jdc_2016_propagation_date_approved: '',
            jdc_2016_renewal_propagation_status: '',
            jdc_2016_renewal_propagation_date_applied: '',
            jdc_2016_renewal_propagation_date_approved: '',
            jdc_2016_deregulation_status: '',
            jdc_2016_deregulation_date_applied: '',
            jdc_2016_deregulation_date_approved: '',

            jdc_2021_transformation_event: '',
            jdc_2021_technology_developer: '',
            jdc_2021_direct_use_status: '',
            jdc_2021_direct_use_date_applied: '',
            jdc_2021_direct_use_date_approved: '',
            jdc_2021_field_trial_status: '',
            jdc_2021_field_trial_date_applied: '',
            jdc_2021_field_trial_date_approved: '',
            jdc_2021_propagation_status: '',
            jdc_2021_propagation_date_applied: '',
            jdc_2021_propagation_date_approved: '',
        };
    }

    static updateForm(oldValue: Partial<Commodity>)
    {
        return {
            id: oldValue.id ?? null,
            breeder_id: oldValue.breeder_id ?? null,
            name: oldValue.name ?? '',
            scientific_name: oldValue.scientific_name ?? '',
            variety: oldValue.variety ?? '',
            accession: oldValue.accession ?? '',
            population: oldValue.population ?? '',
            maturity_period: oldValue.maturity_period ?? '',
            yield: oldValue.yield ?? '',
            description: oldValue.description ?? '',
            photo: oldValue.photo ?? '',
            geolocation: oldValue.location ? oldValue.location.id : '',

            weight: oldValue.characteristics?.weight ?? '',
            length: oldValue.characteristics?.length ?? '',
            width: oldValue.characteristics?.width ?? '',
            shape: oldValue.characteristics?.shape ?? '',

            skin_color: oldValue.characteristics?.skin_color ?? '',
            skin_texture: oldValue.characteristics?.skin_texture ?? '',
            flesh_color: oldValue.characteristics?.flesh_color ?? '',
            flesh_texture: oldValue.characteristics?.flesh_texture ?? '',
            flesh_flavor: oldValue.characteristics?.flesh_flavor ?? '',
            aroma: oldValue.characteristics?.aroma ?? '',

            root_flesh_color: oldValue.characteristics?.root_flesh_color ?? '',
            root_cortex_color: oldValue.characteristics?.root_cortex_color ?? '',
            root_skin_color: oldValue.characteristics?.root_skin_color ?? '',
            root_shape: oldValue.characteristics?.root_shape ?? '',
            tuber_flesh_color: oldValue.characteristics?.tuber_flesh_color ?? '',
            tuber_cortex_color: oldValue.characteristics?.tuber_cortex_color ?? '',
            tuber_skin_color: oldValue.characteristics?.tuber_skin_color ?? '',
            tuber_shape: oldValue.characteristics?.tuber_shape ?? '',

            nsic_registration: oldValue.additionalinfo?.nsic_registration ?? '',
            nsic_registration_number: oldValue.additionalinfo?.nsic_registration_number ?? '',
            nsic_year_approved: oldValue.additionalinfo?.nsic_year_approved ?? '',
            pvp_certificate_number: oldValue.additionalinfo?.pvp_certificate_number ?? '',
            pvp_registration_year: oldValue.additionalinfo?.pvp_registration_year ?? '',

            ncbp_project_type: oldValue.additionalinfo?.ncbp_project_type ?? '',
            ncbp_status: oldValue.additionalinfo?.ncbp_status ?? '',
            ncbp_supervising_ibc: oldValue.additionalinfo?.ncbp_supervising_ibc ?? '',
            ncbp_project_leaders: oldValue.additionalinfo?.ncbp_project_leaders ?? '',
            ncbp_date_approval: oldValue.additionalinfo?.ncbp_date_approval ?? '',
            ncbp_date_completion: oldValue.additionalinfo?.ncbp_date_completion ?? '',

            ao8_transformation_event: oldValue.additionalinfo?.ao8_transformation_event ?? '',
            ao8_technology_developer: oldValue.additionalinfo?.ao8_technology_developer ?? '',
            ao8_direct_use_status: oldValue.additionalinfo?.ao8_direct_use_status ?? '',
            ao8_direct_use_date_applied: oldValue.additionalinfo?.ao8_direct_use_date_applied ?? '',
            ao8_direct_use_date_approved: oldValue.additionalinfo?.ao8_direct_use_date_approved ?? '',
            ao8_field_trial_status: oldValue.additionalinfo?.ao8_field_trial_status ?? '',
            ao8_field_trial_date_applied: oldValue.additionalinfo?.ao8_field_trial_date_applied ?? '',
            ao8_field_trial_date_approved: oldValue.additionalinfo?.ao8_field_trial_date_approved ?? '',
            ao8_propagation_status: oldValue.additionalinfo?.ao8_propagation_status ?? '',
            ao8_propagation_date_applied: oldValue.additionalinfo?.ao8_propagation_date_applied ?? '',
            ao8_propagation_date_approved: oldValue.additionalinfo?.ao8_propagation_date_approved ?? '',

            jdc_2016_transformation_event: oldValue.additionalinfo?.jdc_2016_transformation_event ?? '',
            jdc_2016_technology_developer: oldValue.additionalinfo?.jdc_2016_technology_developer ?? '',
            jdc_2016_direct_use_status: oldValue.additionalinfo?.jdc_2016_direct_use_status ?? '',
            jdc_2016_direct_use_date_applied: oldValue.additionalinfo?.jdc_2016_direct_use_date_applied ?? '',
            jdc_2016_direct_use_date_approved: oldValue.additionalinfo?.jdc_2016_direct_use_date_approved ?? '',
            jdc_2016_ffp_status: oldValue.additionalinfo?.jdc_2016_ffp_status ?? '',
            jdc_2016_ffp_date_applied: oldValue.additionalinfo?.jdc_2016_ffp_date_applied ?? '',
            jdc_2016_ffp_date_approved: oldValue.additionalinfo?.jdc_2016_ffp_date_approved ?? '',
            jdc_2016_field_trial_status: oldValue.additionalinfo?.jdc_2016_field_trial_status ?? '',
            jdc_2016_field_trial_date_applied: oldValue.additionalinfo?.jdc_2016_field_trial_date_applied ?? '',
            jdc_2016_field_trial_date_approved: oldValue.additionalinfo?.jdc_2016_field_trial_date_approved ?? '',
            jdc_2016_propagation_status: oldValue.additionalinfo?.jdc_2016_propagation_status ?? '',
            jdc_2016_propagation_date_applied: oldValue.additionalinfo?.jdc_2016_propagation_date_applied ?? '',
            jdc_2016_propagation_date_approved: oldValue.additionalinfo?.jdc_2016_propagation_date_approved ?? '',
            jdc_2016_renewal_propagation_status: oldValue.additionalinfo?.jdc_2016_renewal_propagation_status ?? '',
            jdc_2016_renewal_propagation_date_applied: oldValue.additionalinfo?.jdc_2016_renewal_propagation_date_applied ?? '',
            jdc_2016_renewal_propagation_date_approved: oldValue.additionalinfo?.jdc_2016_renewal_propagation_date_approved ?? '',
            jdc_2016_deregulation_status: oldValue.additionalinfo?.jdc_2016_deregulation_status ?? '',
            jdc_2016_deregulation_date_applied: oldValue.additionalinfo?.jdc_2016_deregulation_date_applied ?? '',
            jdc_2016_deregulation_date_approved: oldValue.additionalinfo?.jdc_2016_deregulation_date_approved ?? '',
            jdc_2021_transformation_event: oldValue.additionalinfo?.jdc_2021_transformation_event ?? '',
            jdc_2021_technology_developer: oldValue.additionalinfo?.jdc_2021_technology_developer ?? '',
            jdc_2021_direct_use_status: oldValue.additionalinfo?.jdc_2021_direct_use_status ?? '',
            jdc_2021_direct_use_date_applied: oldValue.additionalinfo?.jdc_2021_direct_use_date_applied ?? '',
            jdc_2021_direct_use_date_approved: oldValue.additionalinfo?.jdc_2021_direct_use_date_approved ?? '',
            jdc_2021_field_trial_status: oldValue.additionalinfo?.jdc_2021_field_trial_status ?? '',
            jdc_2021_field_trial_date_applied: oldValue.additionalinfo?.jdc_2021_field_trial_date_applied ?? '',
            jdc_2021_field_trial_date_approved: oldValue.additionalinfo?.jdc_2021_field_trial_date_approved ?? '',
            jdc_2021_propagation_status: oldValue.additionalinfo?.jdc_2021_propagation_status ?? '',
            jdc_2021_propagation_date_applied: oldValue.additionalinfo?.jdc_2021_propagation_date_applied ?? '',
            jdc_2021_propagation_date_approved: oldValue.additionalinfo?.jdc_2021_propagation_date_approved ?? '',
        };
    }

    static getCardColumns() {
        return [
            {
                title: 'ID',
                key: 'id',
                db_key: 'id',
                align: 'center',
                visible: false,
            },
            {
                title: 'User ID',
                key: 'user_id',
                db_key: 'user_id',
                align: 'center',
                visible: false,
            },
            {
                title: 'Breeder',
                key: 'breederName',
                db_key: 'breeder',
                align: 'center',
                class: 'whitespace-nowrap',
                visible: true,
            },
            {
                title: 'Commodity',
                key: 'name',
                db_key: 'name',
                align: 'center',
                visible: true,
            },
            {
                title: 'Scientific Name',
                key: 'scientific_name',
                db_key: 'scientific_name',
                align: 'center italic',
                class: 'italic',
                visible: true,
            },
            {
                title: 'Breeder ID',
                key: 'breeder_id',
                db_key: 'breeder_id',
                align: 'center',
                visible: false,
            },
            {
                title: 'Type',
                key: 'type',
                db_key: 'type',
                align: 'center',
                visible: true,
            },
            {
                title: 'Institution/Agency',
                key: 'breederAffiliation',
                db_key: 'affiliation',
                align: 'center',
                visible: true,
            },
            {
                title: 'Email',
                key: 'breederEmail',
                db_key: 'breeder.email',
                align: 'center',
                visible: false,
            },
            {
                title: 'Contact #',
                key: 'breederMobileNo',
                db_key: 'breeder.mobile_no',
                align: 'center',
                visible: true,
            },
            {
                title: 'Variety',
                key: 'variety',
                db_key: 'variety',
                align: 'center',
                visible: false,
            },
            {
                title: 'Accession No.',
                key: 'accession',
                db_key: 'accession',
                align: 'center',
                visible: false,
            },
            {
                title: 'Population',
                key: 'population',
                db_key: 'population',
                align: 'center',
                visible: false,
            },
            {
                title: 'Maturity Period',
                key: 'maturity_period',
                db_key: 'maturity_period',
                align: 'center',
                visible: false,
            },
            {
                title: 'Yield',
                key: 'yield',
                db_key: 'yield',
                align: 'center',
                visible: false,
            },
            {
                title: 'Description',
                key: 'description',
                db_key: 'description',
                align: 'center',
                visible: false,
            },
            {
                title: 'Location',
                key: 'location.getFullAddress',
                db_key: 'geo_location',
                align: 'center',
                visible: true,
            },
            {
                title: 'Updated At',
                key: 'updated_at',
                db_key: 'updated_at',
                align: 'center',
                visible: false,
            },
            {
                title: 'Created At',
                key: 'created_at',
                db_key: 'created_at',
                align: 'center',
                visible: false,
            },
            {
                title: 'Deleted At',
                key: 'deleted_at',
                db_key: 'deleted_at',
                align: 'center',
                visible: false,
            },
            {
                title: 'Characteristics',
                key: 'characteristics',
                db_key: 'characteristics',
                align: 'center',
                visible: false,
            },
            {
                title: 'Additional Info',
                key: 'additionalinfo',
                db_key: 'additionalinfo',
                align: 'center',
                visible: false,
            },
        ]
    }

    static getColumns(){
        return [
            {
                title: 'ID',
                key: 'id',
                db_key: 'id',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'User ID',
                key: 'user_id',
                db_key: 'user_id',
                align: 'center',
                sortable: true,
                visible: false,
            },
            {
                title: 'Breeder ID',
                key: 'breeder_id',
                db_key: 'breeder_id',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'Breeder',
                key: 'breeder.getFullName',
                db_key: 'breeder.name',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'Commodity',
                key: 'name',
                db_key: 'name',
                keyLabel: 'Commodity',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'Scientific Name',
                key: 'scientific_name',
                db_key: 'scientific_name',
                sortable: true,
                align: 'center italic',
                visible: true,
            },
            {
                title: 'Variety',
                key: 'variety',
                db_key: 'variety',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'Accession No.',
                key: 'accession',
                db_key: 'accession',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'Population',
                key: 'population',
                db_key: 'population',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'Maturity Period',
                key: 'maturity_period',
                db_key: 'maturity_period',
                sortable: false,
                align: 'center',
                visible: true,
            },
            {
                title: 'Yield',
                key: 'yield',
                db_key: 'yield',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'Description',
                key: 'description',
                db_key: 'description',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'Location',
                key: 'location.getFullAddress',
                db_key: 'location',
                sortable: true,
                align: 'center',
                visible: true,
            },
            {
                title: 'Updated At',
                key: 'updated_at',
                db_key: 'updated_at',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'Created At',
                key: 'created_at',
                db_key: 'created_at',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'Deleted At',
                key: 'deleted_at',
                db_key: 'deleted_at',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'Characteristics',
                key: 'characteristics',
                db_key: 'characteristics',
                sortable: true,
                align: 'center',
                visible: false,
            },
            {
                title: 'Additional Info',
                key: 'additionalinfo',
                db_key: 'additionalinfo',
                sortable: true,
                align: 'center',
                visible: false,
            },
        ];
    }
}
