<?php

namespace App\Enums;

class PriorityCommodities
{
    const COCONUT = [
        'name' => 'Coconut',
        'scientific_name' => 'Cocos nucifera',
        'varieties' => [
            'Tagnanan',
            'Laguna Tall',
            'Laguna Dwarf',
            'Laguna Tall x Laguna Dwarf',
            'Laguna Tall x West African Tall',
            'Laguna Dwarf x West African Tall',
            'West African Tall',
            'West African Tall x Laguna Dwarf',
            'West African Tall x Laguna Tall'
        ],
        'germplasm' => [
            'West African Tall (WAT)',
            'East African Tall (EAT)',
            'Indian Tall (West Coast Tall)',
            'Sri Lanka Tall',
            'Panama Tall',
            'Jamaica Tall',
            'Malayan Tall',
            'Malayan Yellow Dwarf',
            'Malayan Red Dwarf',
            'Cameroon Red Dwarf',
            'Fiji Dwarf',
            'Niu Leka (Samoan Dwarf)'
        ],
        'accession' => [
            'WAT 1',
            'WAT 2',
            'WAT 3',
            'WAT 4',
            'WAT 5',
            'WAT 6',
            'WAT 7',
            'WAT 8',
            'WAT 9',
            'WAT 10',
            'WAT 11',
            'WAT 12',
            'WAT 13',
            'WAT 14',
            'WAT 15',
            'WAT 16',
            'WAT 17',
            'WAT 18',
            'WAT 19',
            'WAT 20',
            'WAT 21',
            'WAT 22',
            'WAT 23',
            'WAT 24',
            'WAT 25',
            'WAT 26',
            'WAT 27',
            'WAT 28',
            'WAT 29',
            'WAT 30',
            'WAT 31',
            'WAT 32',
            'WAT 33',
            'WAT 34',
            'WAT 35',
            'WAT 36',
            'WAT 37',
            'WAT 38',
            'WAT 39',
            'WAT 40',
            'WAT 41',
            'WAT 42',
            'WAT 43',
            'WAT 44',
            'WAT 45',
            'WAT 46',
            'WAT 47',
            'WAT 48',
            'WAT 49',
            'WAT 50',
            'WAT 51',
            'WAT 52',
            'WAT 53',
            'WAT 54',
            'WAT 55',
            'WAT 56',
            'WAT 57',
            'WAT 58',
            'WAT 59',
            'WAT 60',
            'WAT 61',
            'WAT 62',
            'WAT 63',
            'WAT 64',
            'WAT 65',
            'WAT 66',
            'WAT 67',
            'WAT 68',
            'WAT 69',
            'WAT 70',
            'WAT 71',
        ]
    ];

    const RICE = [
        'name' => 'Rice',
        'scientific_name' => 'Oryza sativa',
        'varieties' => [
            'NSIC Rc222',
            'NSIC Rc238',
            'NSIC Rc242',
            'NSIC Rc160',
            'NSIC Rc216',
            'NSIC Rc218',
            'NSIC Rc222',
            'NSIC Rc238',
            'NSIC Rc242',
            'NSIC Rc160',
            'NSIC Rc216',
            'NSIC Rc218',
            'NSIC Rc222',
            'NSIC Rc238',
            'NSIC Rc242',
            'NSIC Rc160',
            'NSIC Rc216',
            'NSIC Rc218',
            'NSIC Rc222',
            'NSIC Rc238',
            'NSIC Rc242',
            'NSIC Rc160',
            'NSIC Rc216',
            'NSIC Rc218',
            'NSIC Rc222',
            'NSIC Rc238',
            'NSIC Rc242',
            'NSIC Rc160',
            'NSIC Rc216',
            'NSIC Rc218',
            'NSIC Rc222',
            'NSIC Rc238',
            'NSIC Rc242',
            'NSIC Rc160',
            'NSIC Rc216',
            'NSIC Rc218',
            'NSIC Rc222',
            'NSIC Rc238',
            'NSIC Rc242',
            'NSIC Rc160',
            'NSIC Rc216',
            'NSIC Rc218',
            'NSIC Rc222',
            'NSIC Rc238',
            'NSIC Rc242',
            'NSIC Rc160',
            'NSIC Rc216',
            'NSIC Rc218',
            'NSIC Rc222',
            'NSIC Rc238',
            'NSIC Rc242',
            'NSIC Rc160',
            'NSIC Rc216',
            'NSIC Rc218',
            'NSIC Rc222',
            'NSIC Rc238',
            'NSIC Rc242',
            'NSIC Rc160',
            'NSIC Rc216',
            'NSIC Rc218',
        ],
        'germplasm' => [
            'IR64',
            'IR8',
            'Swarna',
            'MTU1010',
            'Pusa Basmati 1',
            'Koshihikari',
            'Akitakomachi',
            'Sasanishiki',
            'Nipponbare',
            'Hitomebore',
            'Arize Tej Gold',
            'Arize Swift Gold',
            'Arize AZ 7006',
            'Arize AZ 7761',
            'Arize AZ 6799'
        ],
        'accession' => [
            'IR64',
            'IR8',
            'Swarna',
            'MTU1010',
            'Pusa Basmati 1',
            'Koshihikari',
            'Akitakomachi',
            'Sasanishiki',
            'Nipponbare',
            'Hitomebore',
            'Arize Tej Gold',
            'Arize Swift Gold',
            'Arize AZ 7006',
            'Arize AZ 7761',
            'Arize AZ 6799'
        ]
    ];

    const CORN = [
        'name' => 'Corn',
        'scientific_name' => 'Zea mays',
        'varieties' => [
            'White Corn',
            'Yellow Corn',
            'Sweet Corn',
            'Waxy Corn',
            'Popcorn',
            'Flint Corn',
            'Dent Corn',
            'Pod Corn',
            'Flour Corn',
        ],
        'germplasm' => [
            'Pioneer P1197',
            'Dekalb DKC63-90',
            'Syngenta NK800',
            'Mycogen TMF2L825',
            'Channel 213-49STXRIB',
            'Honey Select',
            'Silver Queen',
            'Golden Bantam',
            'Peaches and Cream',
            'Jubilee',
            'Glass Gem',
            'Painted Mountain',
            'Reid’s Yellow Dent',
            'Hickory King',
            'Wapsie Valley',
            'Aztec Black',
            'Oaxacan Green',
            'Cherokee White Eagle',
            'Bloody Butcher',
            'Earth Tones Dent'
        ],
        'accession' => [
            'Pioneer P1197',
            'Dekalb DKC63-90',
            'Syngenta NK800',
            'Mycogen TMF2L825',
            'Channel 213-49STXRIB',
            'Honey Select',
            'Silver Queen',
            'Golden Bantam',
            'Peaches and Cream',
            'Jubilee',
            'Glass Gem',
            'Painted Mountain',
            'Reid’s Yellow Dent',
            'Hickory King',
            'Wapsie Valley',
            'Aztec Black',
            'Oaxacan Green',
            'Cherokee White Eagle',
            'Bloody Butcher',
            'Earth Tones Dent'
        ]
    ];

    const BANANA = [
        'name' => 'Banana',
        'scientific_name' => 'Musa acuminata',
        'varieties' => [
            'Lakatan',
            'Latundan',
            'Saba',
            'Cardaba',
            'Señorita',
            'Bungulan',
            'Morado',
            'Pisang Awak',
            'Pisang Raja',
            'Pisang Mas',
            'Pisang Kepok',
            'Pisang Nangka',
            'Pisang Tanduk',
            'Pisang Barangan',
            'Pisang Uli',
            'Pisang Ambon',
            'Pisang Raja Bulu',
            'Pisang Raja Sereh',
            'Pisang Raja Nangka',
            'Pisang Raja Udang',
            'Pisang Raja Mas',
            'Pisang Raja Kuning',
            'Pisang Raja Kepok',
            'Pisang Raja Tanduk',
            'Pisang Raja Barangan',
            'Pisang Raja Uli',
            'Pisang Raja Ambon',
            'Pisang Raja Nangka',
            'Pisang Raja Udang',
            'Pisang Raja Mas',
            'Pisang Raja Kuning',
            'Pisang Raja Kepok',
            'Pisang Raja Tanduk',
            'Pisang Raja Barangan',
            'Pisang Raja Uli',
            'Pisang Raja Ambon',
            'Pisang Raja Nangka',
            'Pisang Raja Udang',
            'Pisang Raja Mas',
            'Pisang Raja Kuning',
            'Pisang Raja Kepok',
            'Pisang Raja Tanduk',
            'Pisang Raja Barangan',
            'Pisang Raja Uli',
            'Pisang Raja Ambon',
            'Pisang Raja Nangka',
            'Pisang Raja Udang',
            'Pisang Raja Mas',
            'Pisang Raja Kuning',
            'Pisang Raja Kepok',
            'Pisang Raja Tanduk',
            'Pisang Raja Barangan',
            'Pisang Raja Uli',
        ],
        'germplasm' => [
            'Lakatan',
            'Latundan',
            'Saba',
            'Cardaba',
            'Señorita',
            'Bungulan',
            'Morado',
            'Pisang Awak',
            'Pisang Raja',
            'Pisang Mas',
            'Pisang Kepok',
            'Pisang Nangka',
            'Pisang Tanduk',
            'Pisang Barangan',
            'Pisang Uli',
            'Pisang Ambon',
            'Pisang Raja Bulu',
            'Pisang Raja Sereh',
            'Pisang Raja Nangka',
            'Pisang Raja Udang',
            'Pisang Raja Mas',
            'Pisang Raja Kuning',
            'Pisang Raja Kepok',
            'Pisang Raja Tanduk',
            'Pisang Raja Barangan',
            'Pisang Raja Uli',
            'Pisang Raja Ambon',
            'Pisang Raja Nangka',
            'Pisang Raja Udang',
            'Pisang Raja Mas',
            'Pisang Raja Kuning',
            'Pisang Raja Kepok',
            'Pisang Raja Tanduk',
            'Pisang Raja Barangan',
            'Pisang Raja Uli',
            'Pisang Raja Ambon',
            'Pisang Raja Nangka',
            'Pisang Raja Udang',
            'Pisang Raja Mas',
            'Pisang Raja Kuning',
            'Pisang Raja Kepok',
            'Pisang Raja Tanduk',
            'Pisang Raja Barangan',
            'Pisang Raja Uli',
            'Pisang Raja Ambon',
            'Pisang Raja Nangka',
            'Pisang Raja Udang',
            'Pisang Raja Mas',
            'Pisang Raja Kuning',
            'Pisang Raja Kepok',
            'Pisang Raja Tanduk',
            'Pisang Raja Barangan',
            'Pisang Raja Uli',
        ],
        'accession' => [
            'Lakatan',
            'Latundan',
            'Saba',
            'Cardaba',
            'Señorita',
            'Bungulan',
            'Morado',
            'Pisang Awak',
            'Pisang Raja',
            'Pisang Mas',
            'Pisang Kepok',
            'Pisang Nangka',
            'Pisang Tanduk',
            'Pisang Barangan',
            'Pisang Uli',
            'Pisang Ambon',
            'Pisang Raja Bulu',
            'Pisang Raja Sereh',
            'Pisang Raja Nangka',
            'Pisang Raja Udang',
            'Pisang Raja Mas',
            'Pisang Raja Kuning',
            'Pisang Raja Kepok',
            'Pisang Raja Tanduk',
            'Pisang Raja Barangan',
            'Pisang Raja Uli',
            'Pisang Raja Ambon',
            'Pisang Raja Nangka',
            'Pisang Raja Udang',
            'Pisang Raja Mas',
            'Pisang Raja Kuning',
            'Pisang Raja Kepok',
            'Pisang Raja Tanduk',
            'Pisang Raja Barangan',
            'Pisang Raja Uli',
            'Pisang Raja Ambon',
            'Pisang Raja Nangka',
            'Pisang Raja Udang',
            'Pisang Raja Mas',
            'Pisang Raja Kuning',
            'Pisang Raja Kepok',
            'Pisang Raja Tanduk',
            'Pisang Raja Barangan',
            'Pisang Raja Uli',
            'Pisang Raja Ambon',
            'Pisang Raja Nangka',
            'Pisang Raja Udang',
            'Pisang Raja Mas',
            'Pisang Raja Kuning',
            'Pisang Raja Kepok',
            'Pisang Raja Tanduk',
            'Pisang Raja Barangan',
            'Pisang Raja Uli',
        ]
    ];

    const COFFEE = [
        'name' => 'Coffee',
        'scientific_name' => 'Coffea arabica',
        'varieties' => [
            'Typica',
            'Bourbon',
            'Caturra',
            'Catimor',
            'SL28',
            'SL34',
            'Geisha',
            'Mundo Novo',
            'Pacamara',
            'Maragogipe',
            'Pacas',
            'Villa Sarchi',
            'Pache Comum',
            'Pache Colis',
            'Pache San Ramon',
            'Pache Mejorado',
            'Pache Guatemala',
            'Pache Rojo',
            'Pache Azul',
            'Pache Blanco',
        ],
        'germplasm' => [
            'Typica',
            'Bourbon',
            'Caturra',
            'SL28',
            'SL34',
            'Geisha',
            'Pacamara',
            'Blue Mountain',
            'Conilon',
            'S274',
            'Kouillou',
            'Nganda',
            'Baraco',
            'Liberica var. Dewevrei',
            'Catimor',
            'Sarchimor',
            'Ruiru 11',
            'Batian',
            'Centroamericano'
        ],
        'accession' => [
            'Typica',
            'Bourbon',
            'Caturra',
            'Catimor',
            'SL28',
            'SL34',
            'Geisha',
            'Mundo Novo',
            'Pacamara',
            'Maragogipe',
            'Pacas',
            'Villa Sarchi',
            'Pache Comum',
            'Pache Colis',
            'Pache San Ramon',
            'Pache Mejorado',
            'Pache Guatemala',
            'Pache Rojo',
            'Pache Azul',
            'Pache Blanco',
        ]
    ];

    const ABACA = [
        'name' => 'Abaca',
        'scientific_name' => 'Musa textilis',
        'varieties' => [
            'Inosa',
            'Tangongon',
            'Bunulan',
            'Kali',
            'Kabuyao',
            'Tinagak',
            'Bungulan',
            'Kalapin',
            'Lagmay',
            'Binas',
            'Bungulan',
        ],
        'germplasm' => [
            'Inosa',
            'Laylay',
            'Linawaan',
            'Minayog',
            'Pungapong',
            'Abuab',
            'Abuab Hybrid 1',
            'Abuab Hybrid 2',
            'Abuab Hybrid 3',
            'Abuab Hybrid 4',
            'Musa textilis var. textilis',
            'Musa textilis var. lapidi',
            'Musa textilis var. pacol',
            'Tangongon',
            'Linungan',
            'Tinumbaga'
        ],
        'accession' => [
            'Inosa',
            'Tangongon',
            'Bunulan',
            'Kali',
            'Kabuyao',
            'Tinagak',
            'Bungulan',
            'Kalapin',
            'Lagmay',
            'Binas',
            'Bungulan',
        ]
    ];

    const RUBBER = [
        'name' => 'Rubber',
        'scientific_name' => 'Hevea brasiliensis',
        'varieties' => [
            'GT1',
            'PB260',
            'RRIM600',
            'RRIM901',
            'RRIM928',
            'RRIM2020',
            'RRIM2025',
            'RRIM3001',
            'RRIM3005',
            'RRIM3006',
            'RRIM3007',
            'RRIM3008',
            'RRIM3009',
            'RRIM3010',
            'RRIM3011',
            'RRIM3012',
            'RRIM3013',
            'RRIM3014',
            'RRIM3015',
            'RRIM3016',
            'RRIM3017',
            'RRIM3018',
            'RRIM3019',
            'RRIM3020',
            'RRIM3021',
            'RRIM3022',
            'RRIM3023',
            'RRIM3024',
            'RRIM3025',
            'RRIM3026',
            'RRIM3027',
            'RRIM3028',
            'RRIM3029',
            'RRIM3030',
            'RRIM3031',
            'RRIM3032',
            'RRIM3033',
            'RRIM3034',
            'RRIM3035',
            'RRIM3036',
            'RRIM3037',
            'RRIM3038',
            'RRIM3039',
            'RRIM3040',
            'RRIM3041',
            'RRIM3042',
            'RRIM3043',
            'RRIM3044',
            'RRIM3045',
            'RRIM3046',
            'RRIM3047',
            'RRIM3048',
            'RRIM3049',
            'RRIM3050',
            'RRIM3051',
            'RRIM3052',
            'RRIM3053',
            'RRIM3054',
            'RRIM3055',
            'RRIM3056',
            'RRIM3057',
            'RRIM3058',
            'RRIM3059',
            'RRIM3060',
            'RRIM3061',
            'RRIM3062',
            'RRIM3063',
            'RRIM3064',
            'RRIM3065',
            'RRIM3066',
            'RRIM3067',
        ],
        'germplasm' => [
            'RRIM 600',
            'RRIM 703',
            'GT 1',
            'PB 86',
            'PB 260',
            'RRIM 928',
            'RRIM 929',
            'RRIC 100',
            'RRIC 121',
            'PB 330',
            'Hevea brasiliensis var. brasiliensis',
            'Hevea benthamiana',
            'Hevea guianensis',
            'RRIM 2020',
            'PB 350',
            'PR 255',
            'RRIC 102',
            'RRIM 3001'
        ],
        'accession' => [
            'GT1',
            'PB260',
            'RRIM600',
            'RRIM901',
            'RRIM928',
            'RRIM2020',
            'RRIM2025',
            'RRIM3001',
            'RRIM3005',
            'RRIM3006',
            'RRIM3007',
            'RRIM3008',
            'RRIM3009',
            'RRIM3010',
            'RRIM3011',
            'RRIM3012',
            'RRIM3013',
            'RRIM3014',
            'RRIM3015',
            'RRIM3016',
            'RRIM3017',
            'RRIM3018',
            'RRIM3019',
            'RRIM3020',
            'RRIM3021',
            'RRIM3022',
            'RRIM3023',
            'RRIM3024',
            'RRIM3025',
            'RRIM3026',
            'RRIM3027',
            'RRIM3028',
            'RRIM3029',
            'RRIM3030',
            'RRIM3031',
            'RRIM3032',
            'RRIM3033',
            'RRIM3034',
            'RRIM3035',
            'RRIM3036',
            'RRIM3037',
            'RRIM3038',
            'RRIM3039',
            'RRIM3040',
            'RRIM3041',
            'RRIM3042',
            'RRIM3043',
            'RRIM3044',
            'RRIM3045',
            'RRIM3046',
            'RRIM3047',
            'RRIM3048',
            'RRIM3049',
            'RRIM3050',
            'RRIM3051',
            'RRIM3052',
            'RRIM3053',
            'RRIM3054',
            'RRIM3055',
            'RRIM3056',
            'RRIM3057',
            'RRIM3058',
            'RRIM3059',
            'RRIM3060',
            'RRIM3061',
            'RRIM3062',
            'RRIM3063',
            'RRIM3064',
            'RRIM3065',
            'RRIM3066',
            'RRIM3067',
        ]
    ];

    const CASSAVA = [
        'name' => 'Cassava',
        'scientific_name' => 'Manihot esculenta',
        'varieties' => [
            'KU50',
            'KU60',
            'KU70',
            'KU80',
            'KU90',
            'KU100',
            'KU110',
            'KU120',
            'KU130',
            'KU140',
            'KU150',
            'KU160',
            'KU170',
            'KU180',
            'KU190',
            'KU200',
            'KU210',
            'KU220',
            'KU230',
            'KU240',
            'KU250',
            'KU260',
            'KU270',
            'KU280',
            'KU290',
            'KU300',
            'KU310',
            'KU320',
            'KU330',
            'KU340',
            'KU350',
            'KU360',
            'KU370',
            'KU380',
            'KU390',
            'KU400',
            'KU410',
            'KU420',
            'KU430',
            'KU440',
            'KU450',
            'KU460',
            'KU470',
            'KU480',
            'KU490',
            'KU500',
            'KU510',
            'KU520',
            'KU530',
            'KU540',
            'KU550',
            'KU560',
            'KU570',
            'KU580',
            'KU590',
            'KU600',
            'KU610',
            'KU620',
            'KU630',
            'KU640',
            'KU650',
            'KU660',
            'KU670',
            'KU680',
            'KU690',
            'KU700',
            'KU710',
            'KU720',
            'KU730',
            'KU740',
            'KU750',
            'KU760',
            'KU770',
            'KU780',
            'KU790',
            'KU800',
            'KU810',
            'KU820',
            'KU830',
            'KU840',
            'KU850',
            'KU860',
        ],
        'germplasm' => [
            'MCol 22',
            'TME 419',
            'MPer 183',
            'TMS 30572',
            'MVen 77',
            'TMS 4(2)1425',
            'TMS 92/0326',
            'TMS 98/0505',
            'TMS 96/1632',
            'TMS 92/0057',
            'Manihot esculenta ssp. flabellifolia',
            'Manihot esculenta ssp. peruviana',
            'Manihot glaziovii',
            'Cacauzinha',
            'Amarelinha',
            'Araruta',
            'Moti',
            'Branca de Santa Catarina'
        ],
        'accession' => [
            'KU50',
            'KU60',
            'KU70',
            'KU80',
            'KU90',
            'KU100',
            'KU110',
            'KU120',
            'KU130',
            'KU140',
            'KU150',
            'KU160',
            'KU170',
            'KU180',
            'KU190',
            'KU200',
            'KU210',
            'KU220',
            'KU230',
            'KU240',
            'KU250',
            'KU260',
            'KU270',
            'KU280',
            'KU290',
            'KU300',
            'KU310',
            'KU320',
            'KU330',
            'KU340',
            'KU350',
            'KU360',
            'KU370',
            'KU380',
            'KU390',
            'KU400',
            'KU410',
            'KU420',
            'KU430',
            'KU440',
            'KU450',
            'KU460',
            'KU470',
            'KU480',
            'KU490',
            'KU500',
            'KU510',
            'KU520',
            'KU530',
            'KU540',
            'KU550',
            'KU560',
            'KU570',
            'KU580',
            'KU590',
            'KU600',
            'KU610',
            'KU620',
            'KU630',
            'KU640',
            'KU650',
            'KU660',
            'KU670',
            'KU680',
            'KU690',
            'KU700',
            'KU710',
            'KU720',
            'KU730',
            'KU740',
            'KU750',
            'KU760',
            'KU770',
            'KU780',
            'KU790',
            'KU800',
            'KU810',
            'KU820',
            'KU830',
            'KU840',
            'KU850',
            'KU860',
        ]
    ];
}
